### ISSUE TITLE
Read the Docs fails to build

### ISSUE THREAD

**Issue by spigo900** [isi-vista/adam#1016]
For example: https://readthedocs.org/projects/adam-language-learner/builds/12628667/.

**Comment by LichMaster98** [comment]
So technically these issues appear locally if you run `pip install -r requirements.txt` except whatever pip ends up resolving to there seems to function even though the requirements conflict.

**Comment by spigo900** [comment]
@LichMaster98 Thanks for the note. I thought this might be the new [dependency resolver](https://pyfound.blogspot.com/2020/11/pip-20-3-new-resolver.html) but it seems to be older than that and testing locally I don't get the same problem (at least not using `conda` to set up the virtualenv). I didn't test the commands that RTD uses though.

I notice that RTD is trying to use Python 3.7 instead of 3.6, though that's probably not causing the problem.

**Comment by spigo900** [comment]
Actually, looking closer, the Python version might be a problem. It looks like some of the package versions it's trying to install require Python 3.7 or greater, so on 3.6 it wouldn't try to install those versions. So maybe it would help to configure Read the Docs to use Python 3.6 -- then it might be able to find the compatible package versions.

**Comment by spigo900** [comment]
@LichMaster98 Yep, configuring it to use Python 3.6 seems to have fixed the build.
