### ISSUE TITLE
Initial layout for the demo

### ISSUE THREAD

**Issue by gayatri1205** [isi-vista/adam#1025]
![Starter_layout_figma](https://user-images.githubusercontent.com/62416184/132908946-b28d2484-b70b-4c5c-82f8-305aeef6e4c1.png)

Starting point for what the layout could possibly look like.

**Comment by lichtefeld** [comment]
@marjorief I believe this UI looks good as a starting point, do you have any additional thoughts? -- We may end up wanting a view where we can compare specific concepts against each other (e.g. to answer 'how is "ball" different from "spherical block") but we can design the current implementation with the potential for future views in mind.
