### ISSUE TITLE
Minimum Viable Flask API Endpoints

### ISSUE THREAD

**Issue by lichtefeld** [isi-vista/adam#1040]
Below lists the minimum Flask API endpoints as needed by the UI along with any expected input values and the output format. 
These are all `GET` requests as we don't currently have a need to `POST` data.

This issue references data formats as discussed in #1026, #1027, and #1029.

**/api/learners**
Output: 
A list of dicts which for now only have the "name" of the learner. This is future proofing for easier addition of more learner details to display if needed.
```json
{
  "learner_types": [
    {
       "name": "integrated_complete",
    },
  ] 
}
```

**/api/training_curriculum**
Output:
The name of the available training data sets in a list.
```json
{
  "training_curriculum": [
    "objects_single",
    "objects_two_in_scene",
    "etc"
  ] 
}
```

**/api/testing_curriculum**
Same as `api/training_curriculum` except returns the list of test curriculums.

**/api/load_scene**
Input:
```json
{
  "curriculum_name": "objects_test",
  "scene_number": 1
}
```
Comments:
I think this API endpoint should be able to load a scene from the training set and by default we'd probably want the display to show the information after loading. So I think we should, by convention, use the `post_learning` field for the decode on a the test curriculum. Thoughts? I think the format in these fields can just be the output of the `output_language` in this [yaml description](https://github.com/isi-vista/adam/issues/1029#issuecomment-921155932).

Output:
The entire collection of data needed to display a scene on the UI. Including the scene images, the gold standard information, and the learner's output.
```json
{
  "curriculum_name": "objects_test",
  "scene_number": 1,
  "scene_images": [
    "/path/to/scene/img.png",
    "/path/to/scene/img2.png",
  ],
  "post_learning": {},
  "pre_learning": {},
  "gold_standard": {
    "language_with_scene": "a chair",
  }
}
```
--
@gayatri1205 How does this match your current expectations of available end points? Do these endpoints provided the data you're expecting

**Comment by gayatri1205** [comment]
This looks great. As long as we know what data to send to the flask backend, we can figure out how to collect it best. The demo layout in the slides that I referenced initially also had a drop down for pretraining data. Will that have a similar structure as the training data endpoint?
