### ISSUE TITLE
Superimposing co-ordinates of the object strokes on actual image as an overlay

### ISSUE THREAD

**Issue by gayatri1205** [isi-vista/adam#1073]
@lichtefeld and I discussed about the best possible ways of highlighting objects while displaying the scene on the UI, and came up with a possible situation where we could superimpose co-ordinates of the object strokes on the actual image. We would however either need the object co-ordinates to match the actual image, or a mapping between the current modified co-ordinates and the image co-ordinates.

@shengcheng are the co-ordinates of objects in the image in accordance with the images provided by @blakeharrison-ai ? Please let us know!

**Comment by shengcheng** [comment]
Yes. The mean is the center coordinates of the object. And stroke values are relative values.
