### ISSUE TITLE
Annotate ontology objects for their size relative to the learner

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#109]

**Comment by LichMaster98** [comment]
@rgabbard, if `OntologyNodeRelations` are defined as having a `relation_type` and `agr1` is it fine to assume for "bigger_than" that the representation is `BIGGER_THAN(self, arg1)` or should an `OntologyNodeRelation` store `relation_type`, `arg1`, and `arg2` like the SubObjectRelations do? (Where the result would be `BIGGER_THAN(arg1, arg2)`)

**Comment by rgabbard** [comment]
@LichMaster98 : the latter
