### ISSUE TITLE
The 0th prediction is used for all objects if `--dir-num` is specified

### ISSUE THREAD

**Issue by boyleconnor** [isi-vista/adam#1182]
The `else 0` in the line below seems to make it so the prediction for the 0th object of the curriculum will be used for every object in the whole curriculum if `--dir-num` is specified. Why?

https://github.com/isi-vista/adam/blob/a43a362565c8bd30b9622f2662840145b97ef53b/adam_preprocessing/shape_stroke_graph_inference.py#L179

**Comment by spigo900** [comment]
`--dir-num` makes it run on just a single curriculum, so we only have one prediction.
