### ISSUE TITLE
Move size features to `properties`

### ISSUE THREAD

**Issue by boyleconnor** [isi-vista/adam#1210]
As @spigo900 noted in Slack, we want these features to be part of `properties` instead of being ingested directly as `ContinuousNode`s.

**Comment by spigo900** [comment]
Should clarify -- I [did say](https://usc-isi.slack.com/archives/GL17LRSTG/p1668444538434869) properties, but I meant they should become debug attributes `width`, `height`, `box_area` rather than elements of the list of `properties`. `properties` is where they are now.
