### ISSUE TITLE
Track prototypical colors for objects

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#131]
For example, milk is white, juice may be orange or red, etc.  When a color is not explicitly specified for an object in a situation, the perception generator should assign its prototypical color, or one of them if there is more than one.

The prototypical colors should be stored as properties on the ontology nodes.

**Comment by LichMaster98** [comment]
The following are the assumptions I am making about this process.
- The Perceptual Generation should only use a `PROTOTYPICAL_COLOR` as a perceived property if another color was not applied to the object.
- `PROTOTYPICAL_COLOR`s need to be stored as properties on the ontology node

Option 1:
Every `COLOR` node in our ontology gets a matching `PROTO_COLOR` node. `PROTO_COLOR` is a subtype of `PROTOTYPICAL_COLOR` which is an `ABSTRACT, PERCEIVABLE` property. There is a 1:1 map of `PROTO_COLOR` to `COLOR` stored in the ontology. The perception generation then, when it encounters a node that is subtype of `PROTOTYPICAL_COLOR` uses the map in the ontology to add the corresponding `COLOR` node into a set. If the set is not empty we check to see if the object has a color assigned, if not choose a `COLOR` from the list at "random" and then apply it to the object.

Option 2:
Every `COLOR` node in our ontology gets a matching `PROTO_COLOR` node but `PROTO_COLOR` is a subtype of both a specific `COLOR` node and `PROTOTYPICAL`. Then in perception generation, if we encounter a property which is both a `COLOR` and `PROTOTYPICAL` we follow a similar methodology for applying the color except the `COLOR` node is a parent instead. 

Option 2 appears like the implementation time is more work and also introduces multi-parent relationships which some sections of our code specifically call out as "not-supported". However, the advantage I see is that `PROTOTYPICAL` is an abstract property which can then be applied to more than just color in the future.

Option 1 seems like the easier implementation process and mirrors the way a lot of the other properties have been added into the ontology.

**Comment by rgabbard** [comment]
@LichMaster98 : I would suggest an even simpler option:  if an `OntologyNode` has a property which is a sub-type of `COLOR`, then it is interpreted as a the prototypical color for that object.    During percepttion generation:
1. If an object has an explicitly specified color, use it and *do not* translate any colors it may get from the `OntologyNode`
2. If an object does not, randomly choose one of the colors from the `OntologyNode`, if any.
