### ISSUE TITLE
Handle perceptual representation of bi-directional situation relations

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#146]
E.g. contacts(ball, hand)

**Comment by LichMaster98** [comment]
Could this be handled in a similar way to the construction of a StructuralSchema? There we've defined a set of functions which can create symmetric, opposite, and one-way relations.

**Comment by rgabbard** [comment]
@denizbeser : Can you elaborate on this a little bit?

**Comment by denizbeser** [comment]
Within the current perception representation, we have different representations for SituationRelation(CONTACTS, THEME, AGENT), and SituationRelation(CONTACTS, AGENT, THEME) while they should be representing the same concept. It might not be necessary to change this depending on how we build the learner though.

**Comment by rgabbard** [comment]
@denizbeser : A lot of this will have gone away with the new `Region`-based representation of spatial relations, so for the moment I am moving this to the backlog milestone.

**Comment by gabbard** [comment]
This is no longer relevant given the new representation of spatial relations.
