### ISSUE TITLE
Generate language for color modifiers

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#151]

**Comment by LichMaster98** [comment]
@rgabbard The ideal for this would be that the hex code is translated back into the English debug handle for the color. Example: `#4b6f44` is turned into `Green`. The issue I currently see is we lose the color `OntologyNode` during perception translation into hex codes. I've currently added the hex color as a small swatch after the `HasColor` property assertion, should I rework the `HasColor` class to prevent loss of the color `OntologyNode`?

![image](https://user-images.githubusercontent.com/8626833/65156809-b483ca80-d9fd-11e9-9fcf-7f18b92323ef.png)

**Comment by rgabbard** [comment]
@LichMaster98 : The English is generated from the situation representation, rather than the perceptual representation, so you should still have access to the `OntologyNode`.
