### ISSUE TITLE
If an involved person is the speaker, use I/my in language representation

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#154]

**Comment by rgabbard** [comment]
Closely linked to #153

**Comment by rgabbard** [comment]
@denizbeser : split handling _I_ and _my_ into two different issues.  Don't attempt to handle me - throw an exception if the node marked speaker is in anything but the subject position for a verb.

**Comment by rgabbard** [comment]
Note you will need a different verb form when _I_ is the subject.

**Comment by denizbeser** [comment]
closed by #170
