### ISSUE TITLE
Do we need to represent inalienable possession?

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#18]

**Comment by rgabbard** [comment]
@mitchmarcus , do you remember the context for this issue?  I think it was in the context of body parts, but doesn't that decompose into `partOf` + `animate`?

**Comment by mitchmarcus** [comment]
July 17 was  when we first discussed Biederman and discussed
[Slehar's tutorial web page on Biederman](http://cns-alumni.bu.edu/~slehar/webstuff/pcave/biederman.html).
We probably discussed size-small, size-large labels for the first time then, triggered by the tea pot example on that web page.  Actually, the example calls for "smaller than", "larger than", in the description between one part (e.g. a handle) and another (the pot itself) where the left-to-right order of the description seems to be the crucial thing, in this simple string representation.  Your right, we can assume that each body part is smaller than the whole, but we need to note that head is smaller than torso, etc.

**Comment by rgabbard** [comment]
> You're right, we can assume that each body part is smaller than the whole, but we need to note that head is smaller than torso, etc. 

[That we have already, luckily.](https://github.com/isi-vista/adam/blob/master/adam/ontology/phase1_ontology.py#L299)

> We need a way to indicate this for two parts that aren't contiguous. (Two ears should be the same size by default.)

Right now we have `biggerThan` and `smallerThan` which can construct a partial order on sizes, but it is currently only applied between sub-components of a single object.  I've created #83 for handling this problem. It may also require a more sophisticated representation of size than a partial order (#70).

**Comment by rgabbard** [comment]
Closing this issues since we think `partOf` + `animate` covers inalienable possession of body parts.
