### ISSUE TITLE
Handle core vocabulary verb: Throw

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#208]
Throw (~200): PP (60), ADVP (>80), almost always with NP (~180)

Throw: V NP (PP/ADVP)

**Comment by rgabbard** [comment]
@denizbeser :Template examples:
* _A baby throws a truck_ with no goal. 
*  _Dad throws a cookie on the ground_ with a region goal.

I expect there may be issues with binding multiple manipulators, so I'm splitting an animate thing throwing to another animate thing to a new issue.
