### ISSUE TITLE
Specify cross-section type of generalized cylinder base for objects

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#228]
To help distinguish e.g.`ball` from `box`

**Comment by rgabbard** [comment]
@LichMaster98 : Start by reading 117-128 of https://www.dropbox.com/home/ADAM/Papers?preview=RBC+Biederman+1987.pdf

**Comment by rgabbard** [comment]
Notes:

Geon properties:
* does the cross-section have rotational symmetry?
* does the cross-section have reflective symmetry?
* is cross-section curved or straight?
* is primary axis curved or straight?
* is size constant, contracting, expanding, or expand-then-contract?
* whether or not it has a point temrination (p. 124)
* aspect ration

* choice of primary axis: prefer longest, then prefer vertical

* nature of objects joints: 
   * side
   * end-to-end or end-to-side
   * which surface of each is used in the join?

Axis specification:
* terminology primary axis  = _generating axis_.  
* other axes are _orienting axes_
* directed vs symmetric axes
* can mark one axis as aligned with the gravitational axis in the default formulation

**Comment by mitchmarcus** [comment]
If not now, then soon, I'd merge the hollow property by associating it with direction of an axis, typically the generating axis, I suspect.

**Comment by rgabbard** [comment]
@mitchmarcus : Created an issue for this on the post-M3 cleanup milestone: https://github.com/isi-vista/adam/issues/266
