### ISSUE TITLE
Template for over/under

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#234]

**Comment by rgabbard** [comment]
This should be for static situations.  You want templates for small objects under tables (is there anything else in our vocabulary things can be under?).  For over, I think the only things which can be over other things right now are birds?

It is possible we have some of these in the curriculum already, so be sure to check that.

**Comment by denizbeser** [comment]
Yes, looks like table is the only object with HAS_SPACE_UNDER property in the current ontology.
