### ISSUE TITLE
Language generation does not merge in "during" semantics of actions with those explicitly specified in the situation

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#239]

**Comment by rgabbard** [comment]
Once fixed we can remove the `FALL` hack in `_collect_action_modifiers`

**Comment by rgabbard** [comment]
We have to hack around this in the `push` template

**Comment by gabbard** [comment]
@LichMaster98 @denizbeser : Is this still true?

**Comment by gabbard** [comment]
Closed by #704
