### ISSUE TITLE
Person_0 has no connection to torso_0 etc

### ISSUE THREAD

**Issue by mitchmarcus** [isi-vista/adam#243]
It looks like there are body parts for person_0, but they have no relation indicated to person_0

**Comment by mitchmarcus** [comment]
Same with person_1, so it's not a matter of what's visible to our learner apparently (so to speak).

**Comment by rgabbard** [comment]
@mitchmarcus : This is something @elizlee  will cover in #227  - `partOf` relations were taking up so much room we switched to representing it implicitly by nesting in the object list.

(reopen if I have misunderstood)

**Comment by rgabbard** [comment]
(by "representing" I just mean in the HTML dump - they are present as relations in the data structure)
