### ISSUE TITLE
No learner is perceived in some scenes

### ISSUE THREAD

**Issue by mitchmarcus** [isi-vista/adam#244]
The learner is present in the 000-each object by itself and 001 objects with colors scenarios, but suddenly absent in 002 - multiples of the same object, or at least not listed under objects.  Similarly, ground_0 is present in most or all scenarios, but listed under objects in some scenarios and not others.

**Comment by rgabbard** [comment]
@mitchmarcus : Is this for the perception column, the situation column, or both?

**Comment by mitchmarcus** [comment]
Both, I think.

**Comment by rgabbard** [comment]
Okay - on the "situation" side it is okay, because that only shows what is salient to the curriculum writer.  But on the perception side it is a problem.

**Comment by denizbeser** [comment]
It looks like the learner is only perceived when it is actively involved in the situation. So we probably need to add something into the perception code about the learner always perceiving itself. Also need to add a similar component for ground.
