### ISSUE TITLE
Rename "gaze" property to "gazed-at"

### ISSUE THREAD

**Issue by mitchmarcus** [isi-vista/adam#247]
Since table_0 has the +gaze property, I assume that this means not that table_0 is gazing, but that the speaker is perceived to be gazing at it.  Since the gaze property is often on people, the text had better explain this - it isn't otherwise clear whether the property is on the entity gazing or being gazed at.

**Comment by rgabbard** [comment]
@mitchmarcus : Thanks - I've added clarifying this to #227  and renamed this issue to rename the property for `gazed_at` .

Long-term, we may want to shift `gaze` to being a relation: https://github.com/isi-vista/adam/issues/250
