### ISSUE TITLE
Give identical RgbColorPerceptions to sub-objects of the same type

### ISSUE THREAD

**Issue by elizlee** [isi-vista/adam#249]
e.g. currently if we have a car/truck object, each tire will get its own random "black" color (#000000, #343434, #0c020f...)

**Comment by elizlee** [comment]
<img width="510" alt="Screen Shot 2019-09-24 at 5 21 42 PM" src="https://user-images.githubusercontent.com/15387865/65551739-95e76d00-def0-11e9-8fb8-a79f84fcb67c.png">

**Comment by gabbard** [comment]
@elizlee : Did this problem get fixed or is it still present?

**Comment by elizlee** [comment]
@gabbard Still present

**Comment by elizlee** [comment]
Progress has been made (#360); however, now when we have a truck object, its front tires may have a different shade of black from the back tires.

**Comment by LichMaster98** [comment]
![image](https://user-images.githubusercontent.com/8626833/70260600-a15fdb80-175e-11ea-83c2-4d8168e41992.png)

@gabbard In a curriculum export from today this issue is no longer present. I think we can safely close this issue
