### ISSUE TITLE
Properties asserted on regions

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#263]
We are currently propagating properties asserted on regions to their reference objects - we should think more about whether this is the intended behavior.

**Comment by gabbard** [comment]
@denizbeser : can you elaborate on this - perhaps give an example?

**Comment by denizbeser** [comment]
For example, in _"a cup is on the table"_ we create a Region object with _table_ as its reference. Any properties asserted on the region (e.g. table is _below_ the cup) is not a property of Region object but the reference object _table_. I think this behavior is fine as is, but I remember that you wanted me to create an issue for this just in case.

**Comment by gabbard** [comment]
Closing because I can't remember what this was about. :-)

**Comment by denizbeser** [comment]
We were just unsure whether to assign properties to region objects or objects within region objects, e.g. `Region(TABLE)` or `TABLE` in "a ball on the table."

**Comment by gabbard** [comment]
By properties, do you mean things like color? Or relations?

**Comment by denizbeser** [comment]
I believe it is just properties, like color

**Comment by gabbard** [comment]
@denizbeser : Ok. I don't think we support asserting properties on regions, but only on objects.  I'll leave this closed then.
