### ISSUE TITLE
Add proto-roles to action descriptions

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#264]
Agent proto-roles:
![Screen Shot 2019-09-23 at 1 19 40 PM](https://user-images.githubusercontent.com/12912953/65447606-ee414080-de04-11e9-9e9f-0825adcd2fa0.png)

Go:
Agent: Volitional involvement, Movement

Put: 
Agent: Volitional involvement, causes change
Theme: Undergoes change of state
Goal: Stationary

Come: 
Agent: Volitional involvement, Movement

Take: 
Agent: Volitional involvement, causes change
Theme: Change of state

Eat: 
Agent: Volitional, Causing change
Theme: Undergoes change of state

Turn: 
Agent: Movement OR Causing change
Theme: Undergoes change

Sit: 
Agent: Volitional, Movement

Drink: 
Agent: Volitional, causing change
Theme: Undergoes change of state

Push: 
Agent: volitional, causes change
Theme: undergoes change

Fall: 
Agent: Movement

Throw: 
Agent: Volitional, Causing change
Theme: Undergoes change

Move: 
Agent: Volitional, causing change
Theme: Undergoes change of state

Jump: 
Agent: Volitional, Movement

Give: 
Agent: Volitional, Casuses change
Theme: Undergoes change of state

Roll: 
Agent: Volitional, Causes change
Theme: Undergoes change of state

Fly:
Agent: Volitional, movement

**Comment by rgabbard** [comment]
@mitchmarcus : @denizbeser 's draft sub-proto-role information is in the description of this issue

**Comment by rgabbard** [comment]
* for take, I think you should add the things marked with `?`
* for turn, I think just `movement`
* `volitional` for sit, maybe?
* I am not sure the `Agent` of _move_ necessarily moves itself. Ditto `roll`.
