### ISSUE TITLE
Adjacency relations between object sub-parts

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#282]
Why is the only biggerThan/SmallerThan relation for people between torsos and heads.  Should there be more?

**Comment by rgabbard** [comment]
@marjorief : That is coming this evening. :-)

**Comment by rgabbard** [comment]
@marjorief : Actually, this is already there:

```
person_0[is-dad; animate[binary]; self-moving[binary]]
   * head_0
        * in-region(head_0, Region(torso_0,direction=+gravitational))
         * in-region(head_0, Region(torso_0,distance=exterior-but-in-contact))
```

The head is `partOf` the person object; the torso is also part of the person; and the head is above and in contact with the torso. 

Is there something we can do to make this clearer to the reader?

**Comment by marjorief** [comment]
@rgabbard but shouldn't e.g. biggerThan also exist between e.g. torso and leg

**Comment by rgabbard** [comment]
@marjorief : hmm - that's not clear - a torso has more volume than a leg, but is usually shorter.  We restricted size relationships to cases where the difference is very clear, especially since the evidence seems to suggest that kids are only sensitive to large differences in object size.

**Comment by marjorief** [comment]
OK. this seems fine then. I am closing.
