### ISSUE TITLE
the blocks of color in the perceptual rep. should probably be color:"block", ideally with the name of the color in the block (joe olive is color blind). 

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#288]

**Comment by marjorief** [comment]
it looks like there is text when i highlight, but the text is same color as the block so hidden.

**Comment by rgabbard** [comment]
@elizlee : I think you want the text color and the background color to differ. I recommend flipping all the hex pairs to get a contrasting color; if you aren't familiar with hex codes for colors @denizbeser  or @LichMaster98 can probably help.
