### ISSUE TITLE
what can be transparent? 

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#294]
a transparent house

**Comment by rgabbard** [comment]
@marjorief : Can you point to an instance of a transparent house in one of the dump files?

**Comment by marjorief** [comment]
Scene 7 of objects with colors.  It looks like transparent is a color, but it isn't clear that the things that it applies to make sense (also table I think).

**Comment by rgabbard** [comment]
@elizlee : I think this is fixed in the current code; can you do a fresh HTML dump and confirm `transparent` no longer shows up as a color for the object color template?

**Comment by elizlee** [comment]
There is still a house and a table that are transparent in Objects with Colors

**Comment by rgabbard** [comment]
This is caused by #331
