### ISSUE TITLE
In dump description, emphasize that we only mark large differences in relative size with relations

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#295]
learner perception it looks like baby is going to look very much like person, mom, dad. is that true? should we highlight difference?

**Comment by rgabbard** [comment]
@marjorief : I our world right now, a baby is just a very small person.  There's no other difference.  (we are taking baby here to run up to ~2 years old, so they can interact with the world quite a bit)

**Comment by marjorief** [comment]
understood-- i think it is that in its current state, we aren't highlighting absolute size in the perceptual debugging output. If this is coming it is fine, otherwise we might want to have list of things that are perceived but not observed in the summary of the files.

**Comment by rgabbard** [comment]
@marjorief : We only perceive relative size, not absolute, so you will see the difference in size in cases where there is e.g. a baby and an adult in the same scene. I think babies are also smaller than e.g. chairs.

**Comment by marjorief** [comment]
I modified the description of size in the HTML summary.

**Comment by marjorief** [comment]
html summary modified
