### ISSUE TITLE
can liquids fall --- more broadly, issues about liquids. 

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#297]
water, milk, and juice are all falling in intransitives.

**Comment by rgabbard** [comment]
@marjorief : Can you check in these cases whether the perceptual representation has them in a container?  Liquids in bottles falling down in a very frequent kid occurrence. :-)

**Comment by marjorief** [comment]
they also all `fall down` in any object falling.

**Comment by marjorief** [comment]
i don't think that containers are currently represented (but agreed in general)
```
Perceived Objects
ground_0
juice_0[liquid[binary]; inanimate[binary]; Object Color; two-dimensional[binary]; gazed-at[binary]; moves[binary]]
During the action
Paths:
juice_0:
SpatialPath(operator=PathOperator(name='toward'), reference_object=ground_0, reference_axis=None, orientation_changed=False)
```

**Comment by marjorief** [comment]
relatedly, are we assuming that things just fall from the sky.  

`a door falls` ?

**Comment by marjorief** [comment]
and back to liquids and if they are contained:
```Mom gives Dad water``` from transfer of possession 
```
water_0[liquid[binary]; inanimate[binary]; transparent[can-fill-template-slot]; two-dimensional[binary]; gazed-at[binary]; undergoes-change[binary]]
Ø ---> in-region(water_0, Region(hand_0,distance=exterior-but-in-contact))

```

**Comment by mitchmarcus** [comment]
Water, etc, spill.  Containers fall.  Spilling is tricky in that the container is usually not mentioned, nor the goal.

**Comment by marjorief** [comment]
for objects in objects, sometimes liquid is correctly placed in a container (e.g. juice in a cup).  And sometimes it seems like there is an assumed container: `water in a house` `juice in a truck`

**Comment by rgabbard** [comment]
@marjorief : That's a bug where the template is failing to distinguish reasonable sizes - it knows houses and trucks can contain people, but doesn't know it is silly for them to contain liquids
