### ISSUE TITLE
Two Dads, Two Moms

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#299]
discussed this with @LichMaster98 earlier, but given how things are structured, I think we don't want two instances of Dad in the same situation(e.g. Dad gives Dad a chair).

**Comment by rgabbard** [comment]
@marjorief : Can you point to an example where you are seeing this? This should be banned now.

**Comment by marjorief** [comment]
it occurred in the `gives something to someone else` file.  i think it might have occurred elsewhere.

**Comment by LichMaster98** [comment]
@rgabbard According to an up-to-date curriculum dump from master I can't find any evidence of `Mom gives Mom` or `Dad gives Dad` in the possessions file. I think this has been taken care of.
