### ISSUE TITLE
rolling seems to be used in strange contexts

### ISSUE THREAD

**Issue by marjorief** [isi-vista/adam#301]
```
Dad rolls on a truck
a bird rolls on a table
Mom rolls on a table
```

**Comment by rgabbard** [comment]
These are all interpretable but weird, so I'm inclined to call them covered by our warning that we didn't put a lot of effort into making our situations probable.  Does that seem fine?

**Comment by marjorief** [comment]
ok by me.  not sure about the physics of a bird rolling-- but maybe a toy bird.
