### ISSUE TITLE
Objects which are not otherwise supported should rest on the ground

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#309]

**Comment by gabbard** [comment]
@LichMaster98 : Can you elaborate on this, if you remember?

**Comment by LichMaster98** [comment]
@gabbard Yes! And I can provide an example from curricula. Currently, we only add a perceived relationship to the ground if the object has no provided `in-region` relationships from the situation so for the example "a ball beside a box" we assert that the ball is beside the box and the box is asserted as being on the ground, therefor it should be implied that the ball is also on the ground yet this assertion is missing from the perception. 
![image](https://user-images.githubusercontent.com/8626833/69278059-86faff00-0baf-11ea-9694-9fe272085164.png)

**Comment by gabbard** [comment]
Aha, so would an accurate retitling be "objects which are not otherwise supported should rest on the ground" - where all the trick is determining what qualifies as "otherwise supported"?

**Comment by LichMaster98** [comment]
Yes, that would be appropriate. I'll rename this issue.
