### ISSUE TITLE
Subset object learner should extract nouns from utterances

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#361]
The learner should apply to both _the blue truck_ and _the red truck_, as instances of truck; instead of looking for exact matches of observation descriptions.

**Comment by gabbard** [comment]
@denizbeser : Is this issue still applicable since we restructured the sub-set learner to use graph matching?

**Comment by denizbeser** [comment]
Yes, this is still applicable. The learner does not do any operations on the linguistic description, it takes it as a whole and checks the perception hypothesis associated with that specific description. (e.g. line `62 in subset.py`)

**Comment by denizbeser** [comment]
Closing this as the most recent implementation of the pursuit learner iterates over words in each training sentence while learning meanings.
