### ISSUE TITLE
near() relation dsl needs a way of providing a direction to it for situation generation

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#366]
Both _make_object_beside_object_curriculum and _make_behind_in_front_curriculum define a relation which should probably use the `near` DSL however there is not a way to pass the necessary direction information along.

**Comment by LichMaster98** [comment]
Likewise a dsl for `far` could use the same directional information provided to it. Make there should be a new DSL factory for these relations which can require additional information?

**Comment by LichMaster98** [comment]
When this is complete, refine the `Preposition Curriculum` as well as the `Phase 1 Curriculum` to use this DSL, currently, we only define one of the two reciprocal `IN-REGION` relationships manually.

**Comment by LichMaster98** [comment]
Currently, we do exert relationships in both directions on subparts (I.E the `chairback` above the `chairseat` and the `chairseat` below the `chairback`) but if you place a `ball` beside a `chair` we currently only assert that the `ball` is `in-region` of the `chair` with a distance of `proximal` and a direction relative to the `+side-to-side` axis of the `chair`. The inverse of the `chair` being `in-region` of the `ball` with a distance of `proximal` and a direction relative to the `+side-to-side` axis of the `ball` is missing. 

This is missing relationship is because our `near` and `far` DSL for the quick definition of inverse relationships doesn't accept a directional argument. To advance, we are currently hard coding one of the relationships with the primary object being selected as one of the objects at "random" (by random I mean the programmer's choice). Included is a link to the code where a manual definition of the relationship is being defined.

https://github.com/isi-vista/adam/blob/master/adam/curriculum/preposition_curriculum.py#L79-L89

**Comment by gabbard** [comment]
@LichMaster98 : would a better approach here be not to have `near` and `far` but rather put distance arguments on other DSL relations?

**Comment by LichMaster98** [comment]
@gabbard Near and far are useful so long as we can provide a `Direction` to it which was implemented in https://github.com/isi-vista/adam/pull/455

**Comment by gabbard** [comment]
@LichMaster98 : Is there anything remaining to do for this issue then?

**Comment by LichMaster98** [comment]
@gabbard Cleanup Phase1 curriculum generation to use the new features implemented. I implemented this kinda by accident when working on the prepositional curriculum and still need to audit the phase1 curriculum.
