### ISSUE TITLE
Language Generation pluralization for prepositions needs to evaluate better

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#372]
This language generation should say "Dad beside a chair". The second chair in this scene is an extraneous item and not relevant to the preposition. 
![image](https://user-images.githubusercontent.com/8626833/67064131-54389380-f137-11e9-900d-3ddd686638cf.png)

**Comment by gabbard** [comment]
I think for now we want to trigger numeric quantifiers only for scenes with multiples of the same object.
