### ISSUE TITLE
Add the curriculum name to `sorted by utterance length`

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#393]
When I try to render HTML documents sorted by utterance length the HTML files get renamed into `000 - curriculum-sorted-by-utterance.html.html` which isn't useful for determining what file it is.

**Comment by gabbard** [comment]
@LichMaster98 : what was your expectation for how they should be named?

**Comment by LichMaster98** [comment]
@gabbard I suppose I would have expected something like `000 - Preposition Training On - Sorted By Utterance.html` or if we don't plan on sorting the outputs other than by utterance length simply `000 - Prepositions Training On - Sorted.html` Right now I can't tell what the contents of the file are by looking at the file name.

**Comment by gabbard** [comment]
I agree we should include the general curriculum name (e.g. "preposition training"). However, mixing across instance groups happens, so we can't (and shouldn't) distinguish e.g. "preposition Training Beside" from "preposition training on" (if that is what you mean)

**Comment by LichMaster98** [comment]
Fair, I suppose if it's just split into multiple files it's just an arbitrary length -- Maybe it should say "Preposition Curriculum - Sorted` or something like this -- Right now it's not clear if this is the Phase 1 curriculum or the preposition curriculum (which I suppose any curriculum split along training/testing sorted this way isn't useful but knowing that's what I've done is useful)

**Comment by gabbard** [comment]
@LichMaster98 : yes, I agree we should put the overall curriculum name in the filename.

**Comment by LichMaster98** [comment]
While someone is at it, they can correct the double `.html.html` on the end of the file names too
