### ISSUE TITLE
Perception Object Matching needs support for objects which lack schemata

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#422]
List of Objects which can't be instantiated:
* Liquids
* Ground

**Comment by gabbard** [comment]
@LichMaster98 : Can you elaborate on this? What happens if we try to match liquids currently?

**Comment by LichMaster98** [comment]
@gabbard Apologies missed that you had asked this question. We can't currently build a pattern for a liquid from any static function for the pattern. It's possible that the learner would be able to generate a pattern for say "water" based on our proposal of just giving the learner the description "water" and a situation that only contains water. But given `water` doesn't have an object schema I can't add `water` as a detectable object to the default list passed to the preposition learner. This presents issues in trying to identify objects like the preposition `in`

**Comment by gabbard** [comment]
How does this work for the current curriculum examples which have e.g. puddles of water on the ground as noise objects? How are they instantiated in the perception generation without object schemata?

**Comment by LichMaster98** [comment]
I'm unsure how this is being done. I believe @denizbeser wrote that portion of the code and may have an answer?

**Comment by denizbeser** [comment]
If I understand it correctly, the only examples of noise in the curriculum that I know of are in the pursuit curriculum.  where we first create a scene with a complete linguistic description, and then replace the linguistic description, so we have a noisy situation. You can check lines 110-120 in `pursuit_curriculum.py`. Quoting the explanation from that chunk of the code: "A noise instance needs to have the word for our target object while not actually having our target object be present. However, our language generator can't generate irrelevant language for a situation. Therefore, we generate the instance as normal above, but here we replace its linguistic description with the word for the target object."

**Comment by gabbard** [comment]
@LichMaster98 I think what @denizbeser is talking about is something different. Can you do `git blame` on the relevant bits of the preposition curriculum code to figure out where the liquid noise objects are coming from?

**Comment by LichMaster98** [comment]
@gabbard The liquid noise objects in preposition curricula are coming from code I wrote. However, for preposition curricula, I can't give the learner the ability to detect water as a pattern because no static method we provide for generating a `PerceptionGraphPattern` can generate a pattern for an object in our ontology which doesn't have a schema.

**Comment by LichMaster98** [comment]
Additionally, we can not instantiate a pattern for `ground` as it also lacks a schema.

**Comment by gabbard** [comment]
I am closing this issue because #475  is done this will not be significant since we will no longer need to assume innate knowledge of objects before learning prepositions.
