### ISSUE TITLE
Preposition Curriculum Needs Updates from 11/20 Meeting

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#428]
Changes mentioned in the meeting:
- Add `gaze` to the first object in a preposition
- Exclude objects which have the 'hollow' property from the training set unless necessary
- Change the Addressee of any situation to `learner` rather than an additional person in the scene (We don't believe that a 2-year old toddler is capable of prepositions from a perspective other than their own)

**Comment by gabbard** [comment]
@LichMaster98 : can you split this into three distinct issues?

**Comment by LichMaster98** [comment]
This was split into three issues: #432, #431, #430
