### ISSUE TITLE
Should we express "contact"  by a relation rather than a region distance?

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#443]
In defining regions, Landau and Jackendoff distinguish four differences from a reference object: INTERIOR, EXTERIOR-BUT-IN-CONTACT, PROXIMAL, and DISTAL.  

The one tricky case is the distance category EXTERIOR-BUT-IN-CONTACT, which adds the additional requirement of "contactingness" to a purely spatial constraint.  I am wondering if it would be cleaner to diverge from L&J here and just have three distance values, INTERIOR, PROXIMAL, and DISTAL, and to encode contact between objects as a relation.

**Comment by LichMaster98** [comment]
After our discussion on the 27th, we decided to move forward with this idea. 
https://github.com/isi-vista/adam/issues/450

**Comment by gabbard** [comment]
Closed as duplicate of #450
