### ISSUE TITLE
Display AxisInfo on HTML exports so "FacingAddresseeAxis" is clearer

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#453]
During our representation, we sometimes align axis along another axis. One example is `FacingAddressee` where the object is aligned with an Axis of the address, we assign the direction of a region using this relationship and grab the Axis of the addressee for the direction. 

However, other than by IDs, we have no way of knowing which object 'owns' this axis. To solve this issue axis should carry around a link to their owner (SituationObject, Perception, etc) so we can:
* Create a link between the axis and it's owner
* Clarify which axis is appearing in a directional relationship (Explicitly when the axis isn't one of the object's own axes) in the HTML exports

**Comment by gabbard** [comment]
@LichMaster98 : Is there any time other than in dumps when we need to know this?  If only in dumps, can't we build an index in the dumping code?

**Comment by LichMaster98** [comment]
@gabbard We need to know this for the perception graphs so there is a link between the addressee it's axis in the preposition patterns.

**Comment by gabbard** [comment]
@LichMaster98 : Got it - but note here there is also no need to store this on the object itself: we can just add such edges during the perception graph generation process. In fact, don't we add such edges already?

**Comment by LichMaster98** [comment]
@gabbard Hmm, then maybe I need to further investigate why we don't have a link from the Axis which is facing the addressee to the addressee. That link is missing which is a separate issue from the HTML display.

**Comment by gabbard** [comment]
@LichMaster98 : Aha, "facing" is distinct from "ownership" - note the addressee doesn't "possess" this axis. The "facing" information it stored on an `AxesInfo` field on the perception; we should make a separate issue to translate this during perception graph generation.
