### ISSUE TITLE
Integration of preposition learning with object learning

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#475]

**Comment by denizbeser** [comment]
This is still relevant post-M6, especially since we discussed it as an immediate next step in our report.

**Comment by denizbeser** [comment]
@gabbard I'm working a plan for this issue - what are your thoughts on whether we should maintain a subset approach for learning prepositions or create a pursuit-style learning for it?

**Comment by gabbard** [comment]
@denizbeser : we have an existing Pursuit-based learner which works. I think what we want to think through is how to combined pursuit-based learning for both of these at once.

**Comment by denizbeser** [comment]
@gabbard sounds good, thanks!

**Comment by LichMaster98** [comment]
Closed by https://github.com/isi-vista/adam/pull/773
