### ISSUE TITLE
Remove hard-coding of syntax

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#476]

**Comment by gabbard** [comment]
@denizbeser : Can you elaborate on what this issue refers to?

**Comment by denizbeser** [comment]
@gabbard This was listed as "a nice thing to have" in our pre-M6 meeting on December 11th. It was referring to the general idea of learning syntax, instead of automatically generating it the way we have it for English.

**Comment by gabbard** [comment]
I *think* the new template learning paradigm has eliminated explicit hard-coded syntactic knowledge outside of determiners (which we are not targeting for M9).
