### ISSUE TITLE
Pattern intersection will return the full graph when there is only a partial match

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#488]
In [the code for pattern intersection](https://github.com/isi-vista/adam/blob/c6817e67d27a09ced38c8533fd581bce68f57362/adam/perception/perception_graph.py#L589), we only check for the match in one direction. This can cause us to return incorrect results.

**Comment by gabbard** [comment]
We shouldn't address this until #461 is complete to avoid merge conflicts.

**Comment by LichMaster98** [comment]
This might be able to easily be addressed by adding a boolean flag to the function something like `inverse_matched: bool = False` and make the body of the intersection function be something like:
```py
# prior to if unchanged
if inverse_matched and isinstance(attempted_match, PerceptionGraphPatternMatch):
  return self
elif isinstance(attempted_match, PerceptionGraphPatternMatch):
  return graph_pattern.intersection(self, debug_callback=debug_callback, inverse_match=True
else: 
  # unchanged
```

**Comment by gabbard** [comment]
@LichMaster98 : is this bug still present?

**Comment by LichMaster98** [comment]
This bug is no longer present as we now use `matcher.relax_pattern_until_it_matches` for handing the intersection.
