### ISSUE TITLE
Anomalous entries in pursuit curriculum

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#508]
In `m6/pursuit-with-noise/index.html`,

![Screen Shot 2019-12-20 at 10 50 01 PM](https://user-images.githubusercontent.com/7139661/71302605-17795a80-237b-11ea-81ce-cff687ac7077.png)

Note "chair" appears twice in the situation, but the learner's description is "box".

**Comment by denizbeser** [comment]
Noisy learning instances are learning examples where the label of the situation does not match the objects in the situation, such as a scene with two chairs and a ball while hearing the word “box”. In such cases, the learner might learn a noisy-representation, but such representations are eventually eliminated by the pursuit algorithm throughout learning.
