### ISSUE TITLE
Curriculum for simple spatial verbs

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#522]
_go_, _come_, _fall_, _move_, _jump_

**Comment by elizlee** [comment]
Go: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L1216
Come: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L1436
Fall: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L258
Move: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L1117
Jump: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L732

**Comment by gabbard** [comment]
This looks sufficient.
