### ISSUE TITLE
Curriculum for verbs defined by manner

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#523]
in our vocabulary: _roll_, _fly_, _turn_

**Comment by elizlee** [comment]
Roll: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L596
Fly: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L477
We don't have "turn" but we have "spin": https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L1177

**Comment by gabbard** [comment]
This is sufficient.
