### ISSUE TITLE
Curriculum for transfer verbs

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#526]
In our vocabulary: _put_, _give_, _take_, _throw_

**Comment by elizlee** [comment]
Put: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L788
Give: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L305
Take: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L1086
Throw: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L1370

**Comment by gabbard** [comment]
This is sufficient.
