### ISSUE TITLE
Curriculum for _eat_ and _drink_

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#527]

**Comment by elizlee** [comment]
Eat: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L961
Drink: https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L932

**Comment by gabbard** [comment]
This is sufficient.
