### ISSUE TITLE
Determine which pairings of prepositions with verbs in our vocabulary make sense with a dynamic meaning and are in-scope

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#528]
Actions/Verbs: go, put, come, take, eat, give, turn, sit, drink, push, fall, throw, move, jump, has (possessive), give, roll, fly

prepositions/adverbs: to, in, on, beside, behind, in front of, over, under, up, down

**Comment by elizlee** [comment]
**Go**
* {to | in | on | beside | behind | in front of | over | under}: X moves away from speaker with a destination relative to Y (e.g. "A baby goes behind a box")
* {over | under}: X moves with a path across Y ("A dog goes over a chair")
* {up | down}: X moves in some vertical direction ("A bird goes up")

**Put**
* {in | on | beside | behind | in front of | over(?) | under}: X moves Y to a location relative to Z ("Mom puts a ball under a table")
* {up | down}: X moves an object in some vertical direction ("Mom puts a ball down")

**Come**
* {to | in | on | beside | behind | in front of | over | under}: X moves toward the speaker with a destination relative to Y ("A baby comes to a box")
* {up | down}: X moves toward the speaker in some vertical direction ("A bird comes down")

**Take**
* {to | in | beside | behind | in front of | over | under}: X carries Y to a destination relative to Z ("A baby takes a ball in a house")
  * although with most of these prepositions it could be ambiguous with "X takes Y from location relative to Z"

**Turn**
* {to}: X changes orientation to face Y ("Mom turns to a box")
* {over}: X changes orientation of Y such that the vertical axis tilts ("A baby turns over a truck")
* {in | on | beside | behind | in front of | under}: X changes orientation while at a location relative to Y ("A dog turns in a box")

**Sit**
* {down}: X sits ("A dog sits down")

**Push**
* {to | in | beside | behind | in front of | over | under}: X pushes Y to/from a destination relative to Z ("Dad pushes a box in front of a car")

**Fall**
* {to | in | on | beside | behind | in front of | over | under}: X falls and lands somewhere in relation to Y ("A truck falls in a box")
* {over}:
  * X falls such that the vertical axis tilts ("A book falls over")
  * X falls with a path over Y ("Mom falls over a box")
* (we already have "fall down" in the curriculum)

**Throw**
* {to | in | on | beside | behind | in front of | under}: X throws Y where Y lands somewhere in relation to Z (possibly intending for Z to catch Y) ("Mom throws a ball to a baby")
* {over | under}: X throws Y with a path across Z ("A baby throws a cookie over a table")
* {up | down}: X throws Y in some vertical direction ("Dad throws a book down")

**Move**
* {to | beside | behind | in front of | under}: X moves itself somewhere in relation to Y ("Dad moves in front of a baby")
* {to | in | on | beside | behind | in front of | over | under}: X moves Y somewhere in relation to Z ("Mom moves a cookie on a table")
* {over}: X moves (to get out of the way) ("A dog moves over")

**Jump**
* {to | in | on | beside | behind | in front of}: X jumps and lands somewhere in relation to Y ("Mom jumps behind a car")
* (we already have "jump over" in the curriculum)
* {up}: X jumps ("A baby jumps up")
* {down}: X jumps and lands on a lower surface

**Roll**
* {to | beside | behind | in front of | under}: X rolls toward a destination in relation to Y ("A baby rolls under a table")
* {to | in | beside | behind | in front of | over | under}: X rolls Y toward a destination in relation to Z ("Mom rolls a car behind a chair")
* {on | over}: X rolls Y on the surface of Z ("Dad rolls a cookie on a table")
* {over | under}: X rolls (Y) with a path across Z ("A baby rolls a truck over a chair")

**Fly**
* {to | in | on}: X flies toward a destination in relation to Y ("A bird flies in a house")
* {beside | behind | over | under}: X flies with a path relative to Y ("A bird flies behind a car")
* {up | down}: X flies in some vertical direction ("A bird flies up")

**Comment by gabbard** [comment]
> **Go**
> 
> * {to | in | on | beside | behind | in front of | over | under}: X moves away from speaker with a destination relative to Y (e.g. "A baby goes behind a box")

_on_ seems to me to have a special sense with _go_. The others look good.

> * {over | under}: X moves with a path across Y ("A dog goes over a chair")

Would a better typology for `go` be "region of destination vs. region of path". This would put `to`, `in`, `beside` in one class, with `behind/in front of/over/under` having interpretations both ways?

> **Put**
> 
> * {in | on | beside | behind | in front of | over(?) | under}: X moves Y to a location relative to Z ("Mom puts a ball under a table")

As you suggested by your _?_, let's exclude _over_.

> * {up | down}: X moves an object in some vertical direction ("Mom puts a ball down")

Let's skip these. `put up` and to a lesser extent `put down` have special meanings. 
 
> **Come**
> 
> * {to | in | on | beside | behind | in front of | over | under}: X moves toward the speaker with a destination relative to Y ("A baby comes to a box")

hmm - make a separate issue to track _come_.  It doens't work very well with our set of prepositions - you really want _into_ and _out of_.

> * {up | down}: X moves toward the speaker in some vertical direction ("A bird comes down")

Let's omit _up_.

> **Take**
> 
> * {to | in | beside | behind | in front of | over | under}: X carries Y to a destination relative to Z ("A baby takes a ball in a house")

Let's use just _to_ here.

> **Turn**
> 
> * {to}: X changes orientation to face Y ("Mom turns to a box")
> * {over}: X changes orientation of Y such that the vertical axis tilts ("A baby turns over a truck")
> * {in | on | beside | behind | in front of | under}: X changes orientation while at a location relative to Y ("A dog turns in a box")

Let's omit prepositions with _turn_.
 
> **Sit**
> 
> * {down}: X sits ("A dog sits down")

This is fine.
 
> **Push**
> 
> * {to | in | beside | behind | in front of | over | under}: X pushes Y to/from a destination relative to Z ("Dad pushes a box in front of a car")

Omit _over_.
 
> **Fall**
> 
> * {to | in | on | beside | behind | in front of | over | under}: X falls and lands somewhere in relation to Y ("A truck falls in a box")

Omit _to_, _over_, _under_.

> **Throw**
> 
> * {to | in | on | beside | behind | in front of | under}: X throws Y where Y lands somewhere in relation to Z (possibly intending for Z to catch Y) ("Mom throws a ball to a baby")
> * {over | under}: X throws Y with a path across Z ("A baby throws a cookie over a table")
> * {up | down}: X throws Y in some vertical direction ("Dad throws a book down")

These are all good.

> **Move**
> 
> * {to | beside | behind | in front of | under}: X moves itself somewhere in relation to Y ("Dad moves in front of a baby")
> * {to | in | on | beside | behind | in front of | over | under}: X moves Y somewhere in relation to Z ("Mom moves a cookie on a table")
> * {over}: X moves (to get out of the way) ("A dog moves over")

Omit _to_.  Omit _over_ as it has requires a sort of social modeling.

> **Jump**
> 
> * {to | in | on | beside | behind | in front of}: X jumps and lands somewhere in relation to Y ("Mom jumps behind a car")
> * (we already have "jump over" in the curriculum)
> * {up}: X jumps ("A baby jumps up")
> * {down}: X jumps and lands on a lower surface

Omit _to_.  Omit _down_.

> **Roll**
> 
> * {to | beside | behind | in front of | under}: X rolls toward a destination in relation to Y ("A baby rolls under a table")
> * {to | in | beside | behind | in front of | over | under}: X rolls Y toward a destination in relation to Z ("Mom rolls a car behind a chair")
> * {on | over}: X rolls Y on the surface of Z ("Dad rolls a cookie on a table")
> * {over | under}: X rolls (Y) with a path across Z ("A baby rolls a truck over a chair")

Omit _to_.  

> **Fly**
> 
> * {to | in | on}: X flies toward a destination in relation to Y ("A bird flies in a house")
> * {beside | behind | over | under}: X flies with a path relative to Y ("A bird flies behind a car")
> * {up | down}: X flies in some vertical direction ("A bird flies up")

Omit _to_, _on_.

**Comment by gabbard** [comment]
@elizlee : Please make a separate issue and PR for each verb and start working on these curricula.

**Comment by elizlee** [comment]
@gabbard Are we adding a `turn` curriculum, or are those prepositions for `spin`?

**Comment by gabbard** [comment]
@elizlee : Use _spin_.

**Comment by elizlee** [comment]
Oh, right, I forgot that you said to omit prepositions for that

**Comment by gabbard** [comment]
@elizlee : if separate issues have been made for all of these, you can close this issue.
