### ISSUE TITLE
Curriculum for learning I/me/my/you/your

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#530]

**Comment by elizlee** [comment]
I/me/you:
https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L673
I/my/you/your:
https://github.com/isi-vista/adam/blob/c7059410e288d9821971b41efaf76a36d5d2b07a/adam/curriculum/phase1_curriculum.py#L865

**Comment by gabbard** [comment]
@elizlee : I see instances of _you_, but can you point me to the instances of _I/me_?

**Comment by elizlee** [comment]
Ah, I was looking in part at the output.
e.g.
<img width="947" alt="Screen Shot 2020-02-03 at 6 16 53 PM" src="https://user-images.githubusercontent.com/15387865/73699372-a0d9b780-46b1-11ea-8906-9c57acec1643.png">

**Comment by gabbard** [comment]
Aha, got it. We are good then.
