### ISSUE TITLE
Differentiate between "go to" and "go" (near) 

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#569]
Currently our curriculum generation for both "go to" and "go" (near) is very similar. These in fact both render out to the same result. Is there a difference between these and if so how do we represent it? 

"go" (near): https://github.com/isi-vista/adam/blob/master/adam/curriculum/phase1_curriculum.py#L1220-L1232

"go to": https://github.com/isi-vista/adam/blob/549-go-with-prepositions/adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py#L48-62

**Comment by gabbard** [comment]
@LichMaster98 : Is only one of these actually in our phase 1 curriculum? If so, keep that one and don't bother with the other for now, and move this issue to the Phase 2 milestone.

**Comment by LichMaster98** [comment]
@gabbard Both of these are currently in the curriculum depending on which curriculum you reference.

**Comment by gabbard** [comment]
Keep "go near" and drop "go to" because the former is in our formal (phase1) curriculum.
