### ISSUE TITLE
How should we handle prepositional arguments in the situation representation?

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#61]
For example, for _Mom put a ball on a table_, the situation representation represents what is eventually realized as _on a table_ as a relation between the ball and the table which is itself the filler of the `Destination` slot of `put`. Then the language generation code for English special-cases relation argument slot fillers to prepositional phrases when the "subject" of the relation matches the theme of the parent `SituationAction`.

We need a more general solution for this long-term.

**Comment by mitchmarcus** [comment]
If this is from my example, that’s not quite what I meant.  “Loc:(On(ball))”  means that the location is a region returned by “On”.  I believe (after only a little thought, though) that these regions an be returned without reference to the predicate, although perhaps an ambiguous set is returned.  In general, prepositions are functions from objects to either regions or paths (e.g. Toward(table)).  

 

Mitch

**Comment by rgabbard** [comment]
@mitchmarcus : Aren't the representations isomorphic, though?  That is, doesn't

```
put(agent: Mom, theme: ball, goal: On(ball, table))
```

where `On(ball, table)` means "_ball_ is located in the region returned by `On(table)` (to overload the notation) just make explicit the predication of the location of the ball which is implicit in:

```
put(agent: Mom, theme: ball, goal: On(table))
```?

**Comment by mitchmarcus** [comment]
Here's why I think the two notations are different:

"Goal" in Dowty's sense means the place that's the goal of the movement, whereas your notation implies it's the _situation_ that's the result ("goal" in that sense) of the whole action.  

But note that the movement may be complete "put the ball on the table" or incomplete "threw the ball towards the table" (or ambiguous "rolled down the hill" perhaps).  This contrasts with the _result_ of the action `put`, which is indeed

 `On(ball,table)`

Thus I believe, following Landau and Jackendoff, that Goals and Sources are regions.  So for our example, I think we want a function from an object to a region, where the second argument is a region, so better even for the resulting state might be 

`On(ball, Surface(table))`, 

where `Surface` maps from objects to their Surface, and "the ball is on the box" means 

`On(ball, Surface(top(box)))`

 (unless top is assumed a surface, then `On(ball, top(box))` does it.  

This means that the first approximation for "Mom put the ball on the table" is

`put(agent: Mom, theme: ball, goal: On(Surface(table))`

Note that this would allow "Mom threw the ball towards the box" to mean something as fancy as
Agt:mom threw patient:ball1 to a region(x) s.t. x is closer to box1 than region(mom)
If you assume (to make life easier) that it means something like "Mom threw the ball to a region _near_ box1 then you get the much less complex 

`Throw(Agt:Mom, Patient:Ball1, Goal:Near(box1))`
 where `Near` is a function from objects to the region near them -i.e. to a donut shaped region around the object that doesn't include the object.

It also allows us to represent "Mom stuck the ball on the side of the box" if we assume

`Stick(agent: Mom, theme: ball, goal: On(Surface(side(box1)))`

and enrich our earlier representation for "Mom put the ball on the box" to be

`Put(agent: Mom, Patient: Ball, goal:On(Surface(top(box1)))`

**Comment by rgabbard** [comment]
This is now implemented using @mitchmarcus 's proposed representation.
