### ISSUE TITLE
"Bare go" cases lack "to" 

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#676]
It is not very natural as a human utterance.

See situation 868

**Comment by gabbard** [comment]
Phase 1 has a sub-curriculum marked "bare go".  However, it gets rendered in English as something like _A dog goes_, even when there is a semantic `GOAL`. This is not very natural English; I think we should switch it to be something like _A dog goes to Dad_.

**Comment by LichMaster98** [comment]
@gabbard Perhaps we should just invert: https://github.com/isi-vista/adam/issues/569 and only allow an implementation of go which includes a prepositional phrase?

**Comment by gabbard** [comment]
@LichMaster98 : I think that is correct - sorry for making the wrong call there and wasting time. :-). Can you take care of that as your first task for today?
