### ISSUE TITLE
Our semantics for "ball" includes a particular color

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#721]
when it ought not.  Presumably this is a problem with the curriculum?

**Comment by gabbard** [comment]
[a_ball.pdf](https://github.com/isi-vista/adam/files/4382319/a_ball.pdf)

**Comment by denizbeser** [comment]
The html `000 - each object by itself` indicates that the color is present in the perception. The learner probably learns that. Which learner code did you use for this pdf, it might not be a bug?

**Comment by gabbard** [comment]
@denizbeser : I believe `_make_each_object_by_itself_curriculum` is being used. Can you alter it to vary the object colors?

**Comment by denizbeser** [comment]
@gabbard It's already variable, in the html file the colors are different for each objects, and ball appears only once.
