### ISSUE TITLE
Optionally use gaze in pursuit object learning and experiment with ablating its presence

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#734]
- [ ] Modify the Pursuit object learner to (optionally, controlled by a flag on the learner object) give gazed objects a higher chance of being selected as the leading hypothesis.
- [ ] Modify the perceptual generation process to (optionally) introduce noise into the perception of gaze (i.e. omit it with a certain probability; add it spuriously with a certain probability).
- [ ] Create experimental scripts and curricula to explore how the variables of Pursuit learning rate, lexicalization threshold, and gaze ablation probabilities covary. 

You'll probably want to split all three of these off into separate issues and link them to this parent issue.

**Comment by gabbard** [comment]
This is waiting on https://github.com/isi-vista/adam/issues/823

It occurs to me that the pursuit learner currently doesn't check for what objects it already recognizes and block them as hypotheses for other words.  That's probably a good thing to do as a step 0.

**Comment by denizbeser** [comment]
Following up on our discussion with @paynesa - it seems that there are at least two places in the Pursuit algorithm where we can utilize gaze information to improve hypotheses. The first one is boosting an already hypothesized meaning, and most of the changes would probably take place in `probability_of_meaning_given_word` in `pursuit.py` line ~900 (yet to be merged with the new pursuit learner). The second place is prioritizing hypothesizes that corrrespond to the gazed sections of the perception at the initialization step. For object learner, this would mean updating `extract_candidate_objects` (line 494 in `object_recognizer.py`) which is called while generating `hypotheses_from_perception` in `pursuit.py`.

**Comment by gabbard** [comment]
@denizbeser : The second place is clear (to me at least). The first one I am a little fuzzier on: wouldn't the appropriate place there not be "boosting an already hypothesized meaning" but rather when randomly choosing an alternate hypothesis to boost when the leading hypothesis doesn't match?

**Comment by denizbeser** [comment]
@gabbard I see. I think I can clarify the motivation with this example. If we imagine a learner that has an unlexicalized hypothesis for `ball`, that is ready to be reinforced with a likelihood is `probability_of_meaning_given_word`, I think this likelihood should be reinforced _more strongly_ when the learner sees a "ball-with-gaze" scene as opposed to a "ball-without-gaze" scene. It's reinforced in either situation, but a "gazed" reinforcement could be stronger.

**Comment by gabbard** [comment]
Got it. So I think that gives us three dimensions to consider.  This third one opens up a lot of questions about how we modify the update rule, so I suggest focusing on the first two first.

**Comment by gabbard** [comment]
@paynesa : I started working on the "allow ablating gaze" portion of this on a branch, so don't start working on this yet.

**Comment by paynesa** [comment]
@gabbard let me know when you're ready for me to work on this

**Comment by paynesa** [comment]
Here's some results for accuracy vs. number of instances seen over the `M6` curriculum for 5 samples of each object. There are 3 objects in each scene and there are no noise scenes since our noise here comes from the ablation of gaze. 

Currently, `CHAIR` is removed and only 5 samples are used because of #935 

[gaze_ablation_5_instances_per_object.xlsx](https://github.com/isi-vista/adam/files/4963327/gaze_ablation_5_instances_per_object.xlsx)
