### ISSUE TITLE
Curriculum for functionally-defined objects

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#738]

**Comment by gabbard** [comment]
@denizbeser : We don't know what else we want here, but at least go ahead and make a curriculum for _chair_.  Note that for this to be interesting we need to make the chairs shown in a test curriculum different from the chairs seen at training time. Also note we expect our current learning techniques to fail for this, which is okay.

**Comment by denizbeser** [comment]
I'm not sure what this task entails. Should I restructure schema generation (and hence probably how ontology works) such that shapes and sizes are variables?

**Comment by gabbard** [comment]
@denizbeser : I think we want to shoe it a few chairs which have different structural schemas (so it can't just learn the shape) and then test it with more different chairs, so that we can test whether it learns that the fact you sit on something is an important part of the meaning of a chair.

**Comment by denizbeser** [comment]
I see, so I will create a bunch of chairs. How many do you think is enough?

**Comment by gabbard** [comment]
Try three for training and two for testing.

**Comment by LichMaster98** [comment]
Closed by: https://github.com/isi-vista/adam/pull/754
