### ISSUE TITLE
Learn functionally-defined objects

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#739]
Related curriculum: https://github.com/isi-vista/adam/issues/738

**Comment by gabbard** [comment]
Whoever does this should be aware that the curriculum in #738 may need revision if it turns out not to support learning.

**Comment by LichMaster98** [comment]
How to learn:

Enrich all three before we try to learn anything and then create a special case object learner that learns objects based off of the action enrichment.

**Comment by LichMaster98** [comment]
When using the object recognizer we're able to learn these just fine, but we aren't really learning the objects in this case, rather we're just doing the same thing we can already do to learn the verbs.
[m13-functionally-defined-objects.zip](https://github.com/isi-vista/adam/files/4914681/m13-functionally-defined-objects.zip)

**Comment by LichMaster98** [comment]
@gabbard So I'm trying to think through how I can have an ObjectLearner which takes in a graph which has already been enriched by the standard Object, Attribute, Relation, and Verbal learners. The goal is to be able to turn the knowledge that an object which is sat on in the action "sit" is a chair and that a container used when drinking is a "cup".

However, in the case of the 'chair' we would need to first learn "Mom sits" as an action. Then if the learner sees "Mom sits on a chair" we can enrich the scene with "Mom sits" and start trying to process all three unaligned tokens as an object. This approach, however, will 'fail' for the moment as we won't be able to differentiate between "on" and "chair" as the target object language as both will always appear in the utterance. 

Additional complications are handling the fact that the patterns of the chair will look different so we'll need to be able to store multiple patterns for the same target utterance. 

For `drink` the challenge is slightly different. We never have an example which says "Mom drinks from a glass" or "Mom drinks with a glass" so in this case once we learn "Mom drinks" and we don't recognize the cup in the pattern we need some way of being able to say "oh this object used is _normally_ a cup" and then try to start matching the assumed pattern for the cup as that utterance without specifically seeing examples of "cup" with the non-default shape.

**Comment by gabbard** [comment]
@LichMaster98 : I think we want to approach this as follows:

1. We need to add things like `Mom sits on a chair` and `Mom drinks from a cup` to our curriculum; otherwise I don't think we have a way to learn this.
2. Currently I believe that to match a verb pattern we need to have matched objects for all its arguments. This is a problem for this task because we are assuming the _chair_/_cup_ argument has *not* been matched.  I *think* the correct approach for this is to associate `ObjectSemanticNode`s with *all* object roots; we would need some way to distinguish those we have descriptions for from those we do not.  This should allow verb patterns to still match with unknown arguments.
3. We should have a final stage learner which tries to classify unrecognized objects based on the actions the are recognized to participate in.  You could initially just try some simple counting strategy as a learning algorithm (e.g. map to most frequent).
4. Block description-less `ObjectSemanticsNodes` and attributes/relations/actions involving them from getting described.

**Comment by LichMaster98** [comment]
@gabbard On point 2, we currently determine the number of arguments to an action by the number of aligned `Objects` to the utterance. So if we don't know how to align the placeholder `ObjectSemanticNode` for the unknown 'chair' then the verb learner won't get a chance to fail by generating a `slot1_sits_on_slot2` concept instead we'll generate a `slot1_sits_on_a_chair` concept.

Now we may be able to do post-processing to decide that "hey wait, we think that this unlexicalized `ObjectSemanticNode` should *actually* be the chair in the utterance but that seems like a different level of post-processing than you were originally proposing unless I'm misunderstanding?
