### ISSUE TITLE
Curriculum for attributes which constrain actions

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#740]

**Comment by LichMaster98** [comment]
We currently have one good example of this goal in our curriculum. Drink requires learning that you can only drink liquids. We want to be able to demonstrate this task in at least one additional property. 

Upon review of some of our documents, I found another possible example with the verb 'paint' Painting implies a change of property in the form of color to an object in the scene. @gabbard Any thoughts on "paint"?

**Comment by gabbard** [comment]
@LichMaster98 : I'm not sure that quite matches what we need, which is something where the same action is described different ways depending on an object attribute.  I think painting would still be called _painting_ regardless of the object attribute?

**Comment by LichMaster98** [comment]
@gabbard That makes sense. What about the distinction between "roll" and "slide" in that case? If an object is round, then it will roll when placed on a slanted surface while a block (cube) will slide.

Other than that we also have 'eat' in our curriculum which we're currently only teaching as 'eating' objects which are edible.

**Comment by gabbard** [comment]
@LichMaster98 : the trouble here is that "edible" is not a perceivable property for our learner, so it doesn't have an alternate way to describe an agent consuming an inedible object.  

For _roll_ vs _slide_, there is a distinction of manner in the path which the learner uses to make the distinction, rather than an object property.

I think we will need to extend our vocabulary to add another case.

**Comment by LichMaster98** [comment]
After a brief discussion at our zoom meeting, we've decided to implement a small amount of pseudo-german to use the distinction between `Essen` and `Fressen` both of which means "to eat" in English but make a distinction between a human or an animal as doing the action. 

I'll make this curriculum distinction in a `simple_german_curriculum` which includes the two distinctions of "to eat" curriculum. I'll produce a `train` curriculum along with a `test` curriculum.

For additional consideration, @chris-jenkins-isi suggested looking at actions that include non-semantic prepositions. For example "bundle up" or "dress up" and the distinction between the types of clothes used in the action.
