### ISSUE TITLE
Learn imprecise descriptions

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#743]
Related curriculum: https://github.com/isi-vista/adam/issues/new

**Comment by LichMaster98** [comment]
Fixing broken link: https://github.com/isi-vista/adam/issues/742

**Comment by LichMaster98** [comment]
Imprecise size currently has a WIP PR: https://github.com/isi-vista/adam/pull/894
Imprecise Temporal seems to be either not learning or ignoring the important modifier to the SpatialPath as the learner starts saying "fast" and "slowly" for all situations.

[m13-imprecise-size.zip](https://github.com/isi-vista/adam/files/4914789/m13-imprecise-size.zip)
[m13-imprecise-temporal.zip](https://github.com/isi-vista/adam/files/4914790/m13-imprecise-temporal.zip)

**Comment by lichtefeld** [comment]
Closing as ADAM's learner has this learning ability in a limited capacity.
