### ISSUE TITLE
Curriculum for subtle verb distinctions

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#744]
* we proposed the specific example of _throw_/_pass_/_toss_
* we should add several more

**Comment by gabbard** [comment]
@denizbeser : More will be added, but go ahead and set up _throw_/_pass_/_toss_

**Comment by denizbeser** [comment]
@gabbard what are the perceptual distinctions for throw, pass and toss that we can represent?

**Comment by gabbard** [comment]
@denizbeser : I am not sure - try to write up what you think the distinctions are, and then let's determine what we can represent.

**Comment by denizbeser** [comment]
@gabbard going with dictionary definitions:
**Toss:** throw (something) somewhere _lightly, easily, or casually._
**Pass:** Transfer (something) to someone, especially by handing or bequeathing it to the next person in a series
So it's about the manner, which we can't represent as far as I know. The subject's intent and perceptual differences are very subtle, I'm even surprised it can be learned by a young child. If we add adverb functionality, e.g. _smoothly_ we could probably have it work though, where perception of "throw smoothly" is identical to "toss"

**Comment by gabbard** [comment]
@denizbeser : I think we can distinguish `pass` by having a recipient.  Hold off on _toss_ for now.

**Comment by denizbeser** [comment]
Okay, sounds good.

**Comment by LichMaster98** [comment]
Closed by: https://github.com/isi-vista/adam/pull/837
