### ISSUE TITLE
Learn subtle verb distinction curriculum

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#745]
related curriculum: https://github.com/isi-vista/adam/issues/744

**Comment by LichMaster98** [comment]
We seem to do a decent job at learning these.

[m13-subtle-verb.zip](https://github.com/isi-vista/adam/files/4914645/m13-subtle-verb.zip)

**Comment by LichMaster98** [comment]
Semantics are incomplete: https://github.com/isi-vista/adam/issues/910

**Comment by LichMaster98** [comment]
After translating spatial paths we can learn these semantics correctly now. 
[m13-subtle-verb-v3.zip](https://github.com/isi-vista/adam/files/4926123/m13-subtle-verb-v3.zip)
