### ISSUE TITLE
Curriculum for dynamic prepositions 

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#748]
e.g. _towards_

**Comment by gabbard** [comment]
Upon completion change title to "Learn... " and shift to next milestone.

**Comment by LichMaster98** [comment]
Below is the list of Dynamic Prepositions / Adverbs that we promise in our Phase 2 curriculum report. 
- [ ] Towards
- [ ] Away
- [ ] In
- [ ] Into
- [ ] At
- [ ] Out
- [ ] To

**Comment by LichMaster98** [comment]
@gabbard 

Our current subset-verb learner should be capable of learning these relationships *as part of a solution for a verb* but that doesn't learn the relationship independently where we could say train the learner on "towards" with go, try fly without any "towards" examples, and then test for "fly towards"

I think the learning hypothesis space for these dynamic prepositions still fits our learning model of the `relationship` learner. For example, consider the situation "a dog pushes a cup toward a door" (situation 52 of Push + PP curriculum from branch #767 ) if we could leave all the perception information the same but only isolate the English of "a cup toward a door" then our relational learner would be able to identify the "cup" and "door" as the two `slots` of the relationship. 

Then we try to isolate the shortest path between the two nodes. Which in this case should be both a regional relationship and a spatial path. Both should have a length of 1 between the two search nodes. The subset learner should be able to eventually remove the regional relationship as being part of "towards" when presented with a situation where we end in another prepositional relationship. (Say "a dog pushes toward a door a cup to the box" - kind of ugly English.)

The same type of connection should exist for "away from". For "out" the issue that occurs to me is that we understandable do not add the negated relationships. So for this preposition, we can learn that temporally scoped "before" gives a relationship of inside and then "after" needs to NOT include this relationship. But given our patterns don't really have a way of learning this the subset learner would quickly get confused and learn "out" is simply anything that "in" with the before temporal scope when that wouldn't be quite right. We'd need to enrich the patterns' ability to store a "don't find this pattern" type of understanding.

**Comment by LichMaster98** [comment]
Closed by https://github.com/isi-vista/adam/pull/767
Learning being tracked in: https://github.com/isi-vista/adam/issues/769
