### ISSUE TITLE
Handle Chinese Classifiers

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#782]
This has implications for count/mass noun distinction.

**Comment by paynesa** [comment]
Classifiers should be checked by a native speaker upon implementation

**Comment by paynesa** [comment]
From what I'm able to find online (should definitely be checked by a native speaker), we have the following options for Chinese classifiers for the objects in the Phase 1 ontology:

* 辆 classifies automobiles: `CAR, TRUCK`
* 只 classifies animals and objects that are one of a pair: `BIRD, DOG, HAND`
* 张 classifies flat objects and faces: `TABLE` (potentially `GROUND` but I don't think we want to count grounds)
* 本 classifies bound volumes: `BOOK`
* 间 classifies rooms and spaces: `HOUSE`
* 杯 classifies cups of liquid (you can add it to `WATER, MILK, JUICE` to count cups of them)
* 把 classifies things that you use with your hands and chairs: `HOUSE`
* 扇 classifies windows and doors: `DOOR`
* 顶 classifies things with protruding tops or things you put on your head: `HAT`
* 块 classifies things with irregular shapes/chunks: `COOKIE` 
* 个 classifies people and individual objects: `MOM, DAD, BABY, BALL, BOX, HEAD, CUP`

个 is generally considered an okay classifier to use if you don't know the proper classifier for something -- it's an acceptable catch-all for learners of Chinese. 

I'm not sure that there's enough objects attributed to each classifier in our phase 1 ontology for our learner to even acquire these classifier-to-property mappings, especially since many of them only classify one object in our ontology. 

Many of these are far too specific to use properties from the ontology node to generate the correct classifier so I don't think our language generator can rely on this. Instead, I think the best way to proceed is to add a field to `LexiconEntry` to store the classifier for each entry when it's generated. This will be similar to how the 3rd person singular of a verb is implemented in English and we can leave it empty for those that take 个 and make that the default for ease of use.

**Comment by gabbard** [comment]
This seems like a fine approach. These are going to be difficult for us to learn in a generalized way!
