### ISSUE TITLE
Handle Chinese Obliques

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#790]
According to https://wals.info/chapter/84, Chinese generally has an XVO construction for obliques. However, there are several caveats. Namely:

1. Non-ditransitive verbs in Chinese don’t allow 2 objects to occur after the verb, so one is moved to the preverbal position as an oblique, preceded by “ba.” For example, “I give you a present” but “you (ba)book put at-table-on” There is a obl:patient universal dependency tag we could use for this construction, but I’m not sure if we necessarily need to given that this is still in XVO construction. 
 
2. Adverbs typically occur between X and V, except in the case of negation in “ba” clauses in which the adverb must come before “ba"-- this is where the "ba" clauses become more of a problem (https://resources.allsetlearning.com/chinese/grammar/Using_%22ba%22_sentence). It’s valid to place adverbs before all “ba” clauses with slightly different meaning than after, so I’m not sure how to handle this without either having two adverb slots or using the obl:patient tag (or ignoring negation?). 
 
3. Duration or frequency obliques can occur after a verb as long as there’s not also an object (e.g. “I ran 3 days” = “I ran for 3 days”). I’m really struggling on how to handle this. We could, for instance, use the obl:temp modifier, but I’m not sure how much this would help vs. overcomplicate things. 

Right now, I've put the obl in the XVO position, but I think we still need to handle the other cases above (and probably have a native speaker check them). This solution necessarily takes out a lot of the noise in the data re oblique locations, which could be a good thing for our learner but is also arguable a hack.

**Comment by gabbard** [comment]
@paynesa : Nice write up!  

For (1) The way we represent things with universal dependencies is entirely language-generator-internal, so feel free to do whatever is easiest.  For (2) and (3), I am not sure adverbs and duration/frequency obliques are in-scope for ADAM, so I think you can just not handle them at all for the moment (do we handle them on the English side?)

**Comment by paynesa** [comment]
@gabbard Sounds good! I'll leave this as-is for now but keep the issue open until it's verified that this is ok by a native speaker. From the English testing files, it looks like we don't handle (2) and (3) currently.
