### ISSUE TITLE
English-specific assumptions about attribute candidates

### ISSUE THREAD

**Issue by spigo900** [isi-vista/adam#791]
[Currently][attribute_candidates_assumption] we make the assumption that the word immediately before and the word immediately after each object in an utterance are candidate attributes. This works for English but may not hold for other languages we want to use.

[attribute_candidates_assumption]: https://github.com/isi-vista/adam/blob/40b09514e433bad4fc6b72da95d008e22a059d26/adam/learner/attributes.py#L60

**Comment by spigo900** [comment]
@gabbard To be clear, what is the English-specific assumption here? Is it the assumption that one or both of these surrounding words will be candidates? Or is it that other words are *not* considered as candidates when they should be in another language?

**Comment by mitchmarcus** [comment]
I think this is more universal than you think.  Except for languages with lots of scrambling, which requires lots of case marking, the modifiers are right next to the noun.  (Charles, do I have this right?)

 

Mitch

**Comment by LichMaster98** [comment]
We should note checking only one position over will limit our ability to learn attributes from a sentence like "a big red dog" as 'big' is more than one position away from 'dog' -- However, this is a more complicated assertion so it may be out of scope.

**Comment by gabbard** [comment]
@mitchmarcus : Correct - the note was more "I should check with @mitchmarcus  and @charles-yang-upenn that my intuition that this is fairly universal is correct" :-)

**Comment by gabbard** [comment]
@LichMaster98 : the `big red dog` case is covered by https://github.com/isi-vista/adam/issues/785

**Comment by charles-yang-upenn** [comment]
Sorry for being late to the thread but I agree with what @mitchmarcus and @gabbard  said earlier.

**Comment by gabbard** [comment]
Closing on agreement re: universality
