### ISSUE TITLE
Handle localizers vs. prepositions in Chinese

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#795]
Chinese indicates location (e.g. in the case of "put the book on the table") with localizers which attach at the end of NP's rather than the beginning like prepositions (i.e. "the book put the table on"). If we want to indicate prepositions that can't be indicated with localizers, we'll need two separate ways to indicate this.

**Comment by paynesa** [comment]
http://ling.auf.net/lingbuzz/002063/v3.pdf mentions that many scholars consider localizers to function similar to nouns so right now I'm considering them as nominal modifiers to the NP that they modify, since universal dependencies doesn't have their own tag for them and they're likely an autonomous category.

**Comment by gabbard** [comment]
@paynesa : That seems like a reasonable solution.
