### ISSUE TITLE
Guaranteed goal and Dao vs. Zai distinction 

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#796]
In Chinese, I believe localiser phrases (similar to English PP's) depend on whether the verb guarantees an end location or not. If there is no end location guaranteed, we use "dao," but if there is a guaranteed one, we use "zai." For example: 

push, take (to), move (to), jump (onto), fly, throw all take "dao"

put, sit, fall (onto) all take "zai"

We need a way to distinguish between these two for the Chinese language generator. There's already an open issue (#582) about roll, take, fall, fly, jump not taking GOALS, and all of these are also "dao" verbs, which means that we could potentially use this as a distinction. However, from a user interface POV, this might not be ideal for reasons discussed in #582.

Other options include the in-region distinction.

**Comment by gabbard** [comment]
@paynesa : All your `zai` examples seem to be cases where the theme ends up being physically supported by the object at its end location. Can you tell whether this is true in general or not?

**Comment by paynesa** [comment]
@gabbard according to a native speaker, "dao" indicates motion towards an object, while "zai" indicates a static result, so it's valid (but less used) to use put with "dao" since there is a change in motion there. From native speaker:
_______
Generally, in Chinese, “到” (dao) indicates the object is from somewhere else to the location you mentioned and stops there. For example, I move the book to the table (我把书移到桌子上), means the book is not on the table initially but after the verb, it is to the location you mentioned (table).

And to the “在” (zai) in Chinese, it means the object is being at the location and we don’t care about or don’t know the initial location where it is (there is no motion for the objects). So, I am eating on the table (我在桌上吃饭) means eating is happening on the table now.
________
Notably, "zai" is used any time we're expressing where an action is taking place (for example, with I'm eating on the table where there's no change in location involving the table). I think the use of zai vs. dao outlined in my original post makes sense given the above, since when you sit on something, you don't typically care where you were the instant before, and once something has fallen or is put, it's in a static location, while the "dao" verbs have less of a clear endpoint. However, I'm still not sure how to make this distinction. after_action_relations could definitely be used, perhaps in contrast to before_action_relations? I think the above information means that the GOAL can't be used as a distinguishing factor since both have salient GOALs semantically.

**Comment by gabbard** [comment]
@paynesa : Maybe the following would work:
* the location is only mentioned at all if it is marked as a salient object in the situation
* use _zai_ be default.
* use _dao_ if there is an `after_action` relation between the theme and a region which has the salient location object as its reference object, but no such relationship is present in either the before_action relations or the enduring relations (that is, this relationship is new).

**Comment by paynesa** [comment]
@gabbard That makes sense, thanks!

**Comment by paynesa** [comment]
We currently do the following:

1. `always_relations` indicate preverbial localiser phrases and NP modification with localiser phrases. They always use `zai` since the location will not change (https://github.com/isi-vista/adam/issues/811)

2. `after_action_relations` are translated postverbially to `dao` since this is an indication of a change of state that we care about.

3. `during.at_some_point` relations are translated postverbially to `gwo` which indicates motion past a point rather than to it.

4. Everything else is translated post-verbially with `zai`.
