### ISSUE TITLE
Distinguish those properties which should be perceivable to the learner

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/adam#80]
- we need to allow `OntologyProperty`s to themselves have properties of some sort.
- these can be used to indicate which properties of objects should be passed along to the the perceptual representation directly and which should be filtered out

**Comment by denizbeser** [comment]
@rgabbard I'm thinking of adding a boolean indicator to the ObjectProperty class indicating whether a property is perceivable. So far we have 4 properties. I think "animate", "inanimate" and "sentient" are learned properties (i.e. not available to the learner, not perceivable) and "recognized_particlar" is perceivable. What do you think? Do you think that's enough or do we need a more complicated representation? Thanks!

**Comment by mitchmarcus** [comment]
I believe we're assuming kids know these properties innately.

**Comment by rgabbard** [comment]
@denizbeser : @mitchmarcus is correct - we are assuming `animate`, `inanimate`, and `sentient` are perceivable as well.

The boolean representation is good for now.  Eventually if we want to support ablation of what is and isn't perceivable we will need something more sophisticated but that bridge can be cross after the M3 milestone.

**Comment by denizbeser** [comment]
Got it, thanks!

**Comment by rgabbard** [comment]
This information was added to the ontology in #84 .  Once https://github.com/isi-vista/adam/pull/81 is merged, the actual filtering of perceivable properties can be added there.

It occurs to me we should add a similar flag for relations.
