### ISSUE TITLE
Run experiments over the new integrated learner to compare with the Phase1 learners

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#801]

**Comment by gabbard** [comment]
@LichMaster98 : Can you link this to issues for any outstanding problems? (or close it, if we're done)

**Comment by LichMaster98** [comment]
@gabbard If the intent of this issue is to be able to run the Integrated Learner with a non-ObjectRecognizerAsObjectLearner then: https://github.com/isi-vista/adam/issues/869 is the only current outstanding issue.

Other than that, both the ObjectRecognizer portion and the other three learners function independently.

**Comment by gabbard** [comment]
Okay, I will close this then.
