### ISSUE TITLE
Counts including non-salient objects when they shouldn't

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#802]
For both English and Chinese, if we have 2 of the same objects, one salient and one not, our counts are currently taken across non-salient and salient objects. This means that if there are, say, 2 trucks in a situation, one of which is salient, we will end up generating language for "two trucks" rather than "a truck" referencing only the salient truck.

**Comment by gabbard** [comment]
@paynesa @LichMaster98 : Would it make sense for @denizbeser to look at this since he is working on plurals in general?

**Comment by paynesa** [comment]
@gabbard sure, I fixed the issue mostly for Chinese by only counting salient objects, but I don't think it's been fixed for English yet and I'm not sure if my fix for Chinese was the best solution.

**Comment by gabbard** [comment]
@paynesa : Thanks - can you link to the relevant code for your Chinese fix in a comment here?

**Comment by paynesa** [comment]
https://github.com/isi-vista/adam/blob/95122d4ba1c60adece2cf9baa31143bb324cbb5a/adam/language_specific/chinese/chinese_language_generator.py#L1207 
and I updated above/below implementation for our learner and curricula to be compatible with this, you just have to add the second object as salient

**Comment by paynesa** [comment]
See https://github.com/isi-vista/adam/blob/95122d4ba1c60adece2cf9baa31143bb324cbb5a/tests/language_specific/chinese/test_chinese_language_generator.py#L2550 and the test cases near it for examples of the above+below update
