### ISSUE TITLE
Learn Object restrictions

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#809]
We would like to demonstrate that out learner and acquire an understanding of the restrictions on objects which can be involved in actions.  

I believe we can do this once [my proposed solution](https://github.com/isi-vista/adam/issues/502#issuecomment-644280733) to https://github.com/isi-vista/adam/issues/502 is implemented.  At that point our verb patterns will be able to "reach insider" objects and match against sub-sections of them.  For this to work, there must be some sort of perceptual correlate of the restriction an verb places on its arguments.

**Comment by spigo900** [comment]
@gabbard This should be unblocked now now that #502 is closed.

Re: perceptual correlates, are [these commented out relations](https://github.com/isi-vista/adam/blob/693924403a5c64fce4e4bc6bec97331260dc3a30/adam/ontology/phase1_ontology.py#L1989) the sort of thing you mean? Example: "A giver must have a manipulating part that is touching the gift before the action and is not touching the gift after the action."

**Comment by gabbard** [comment]
@spigo900 : More "something must have a round shape in order to roll" - @LichMaster98 @denizbeser , do you remember the other thing like this we added to the curriculum?>

**Comment by denizbeser** [comment]
@gabbard I think containers (capability of holding things with the example of "put in") was the other one we had.

**Comment by denizbeser** [comment]
We can successfully learn the "hollow" constraint with "put in", but we fail to learn "circularity" since it's a _subproperty_ of Geons, which are removed from matched patterns as the Geon nodes do not match completely. This will require us to split Geons into its components in the perception graph.

**Comment by denizbeser** [comment]
This works with the ObjectRecognizer, but not with the ObjectLearner. I will look into the specifics of what is missing from the learned hypotheses for objects that prevents learning these specific verb templates.
