### ISSUE TITLE
Make sure the integrated learner can learn attributes

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#813]
The M9 learner seems to fail for attributes - the learner doesn’t really seem to update what it learns. It learns the things correctly at first, but doesn’t learn a new color once it associates a set of attribute with a certain object. 

We want to make sure this isn't an issue for the new learner.

**Comment by LichMaster98** [comment]
The integrated learner is capable of learning colors well over static situations. The attribute learner does modify the state of the colors as presented with new information for a given color. This will be closed by #803
