### ISSUE TITLE
Fix Chinese implementation for integrated learner

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#820]
The implementation is really hackish right now and doesn't work very well since there are multiple classes referring to the English nodes so the Chinese lexical conversion has do be done in post-processing which we need to change.

**Comment by LichMaster98** [comment]
@paynesa Does #865 solve this issue completely?

**Comment by paynesa** [comment]
@LichMaster98 yes. The learning of e.g. "dad has a head" is still hackish but this is because of the nature of the template not the learner.
