### ISSUE TITLE
Differential "tall" and "small" by being able to assert difference in sizes of an object axis

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#832]

**Comment by paynesa** [comment]
We now differentiate with the relative size of the axes, but the learner ends up hypothesizing almost identical semantics for both (examples attached). 

[short_slot1.0.pdf](https://github.com/isi-vista/adam/files/5071666/short_slot1.0.pdf)
[small_slot1.0.pdf](https://github.com/isi-vista/adam/files/5071667/small_slot1.0.pdf)
