### ISSUE TITLE
Learning of NP's with Localisers under Integrated Model in Chinese

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#834]
The `_candidate_templates` method of the `AbstractRelationTemplateLearnerNew` class used for preposition/localiser acquisition in the Integrated Learner, we can either handle prepositions or post-positions, which works well for English but not for Chinese. For example, in Chinese, we have "zai Y shang de X" meaning "an X on a Y" but our learner only extracts "Y shang de X" due to its nature. This is not a problem when using the regular `SubsetPrepositionLearner.`

**Comment by LichMaster98** [comment]
@paynesa So if I'm understanding correctly `zai` (the portion getting lost) is important for identifying the `on` relationship and isn't just a determiner -- In that case we need to reconsider our hypothesis space for the relationship learner -- and probably design it to be closer to the verb learner. 

The previous learners simply took the entire token sequence presented to them and turned it into the template for the hypothesis which we knew at the time was mostly a hack for that learner.

**Comment by paynesa** [comment]
@LichMaster98 yes so for Chinese, there's both a localiser and a coverb and together they give the information given by a preposition in English (in this case zai is the coverb and shang is the localiser, and we need both to have a complete phrase). 

Since `SubsetVerbLearnerNew` also implements `AbstractRelationTemplateLearnerNew`, I think it will cause the same problem, right? i'm a little confused about where the difference in the implementation is.

**Comment by paynesa** [comment]
Same issue occurs with attributes. In Chinese, we have "wo de" = my and "wo" = me/I, and the attribute learner cannot learn "wo de" and just learns "de" instead.

**Comment by LichMaster98** [comment]
@paynesa The verb learner should be able to handle the multi-word phrases it's more robust in how it decides to create it's hypothesis.

For the phrase "wo de" could you make that a single token rather than two? We have a few phrases like this in English (e.g. "in front of") where we treat the phrase as a single token in the tuple rather than three entries? If you do, start a list in: https://github.com/isi-vista/adam/issues/826 for Chinese.

**Comment by paynesa** [comment]
@LichMaster98 that makes sense, thanks! We could absolutely make "wo de" one token.

**Comment by LichMaster98** [comment]
Yeah @paynesa I think that's the best move for this moment, considering we treat some of the English tokens like this.

**Comment by paynesa** [comment]
@LichMaster98 This works, however, can we currently handle 3rd person possessives in our integrated learner for English? Chinese possessives are basically the same except with "de" instead of 's, but if "de" didn't work for wo de and ni de, then I expect it wouldn't work for the third person possessive unless 's is a part of the possessor string.

**Comment by LichMaster98** [comment]
@paynesa  I don't believe we currently handle 3rd person possessive in English, we only cover "my" and "your".
