### ISSUE TITLE
Current verb learners cannot learn Chinese post-verbial localisers

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#866]
Our current `IntegratedLearner` implementation cannot learn "put" or "throw" in Chinese which both use post-verbial localiser phrases. For example, "X puts Y on Z" is expressed in Chinese as "X ba Y fang dzai Z shang" and our learner currently does not learn the "ba Y" part of this and rather substitutes some item's name it has encountered during learning into the slot. The errors are even worse for throwing since there is more syntactic variation among the examples the learner encounters, and so "throwing" in Chinese fails for both the `IntegratedLearner` and `SubsetLearner` with the `SubsetLearner` coming up with no hypotheses and the `Integrated` one only coming up with very short ones. Localiser phrases that occur preverbially are learned just fine, so this is a specific issue to post-verbial localiser phrases.

**Comment by LichMaster98** [comment]
@paynesa This should be able to be fixed by allowing permutations of verb templates with 3 arguments and 3 fixed strings here: https://github.com/isi-vista/adam/blob/master/adam/learner/verbs.py#L154-L162

Adding an additional reference to `FixedString` along with incrementing the num param to 6 should allow us to hopefully learn these instances.

Can you see if this solution works without breaking anything else?

**Comment by paynesa** [comment]
This fixes "put" and all instances of "throw" except `X throws Y to Z`. In this case, we have an issue with animacy in Chinese which doesn't translate to English: in English, both "I throw the ball to you" and "I throw the ball to the cup" are acceptable since "to" carries slightly different meaning in each. However, in Chinese, we would use "gei" in the first one and "dao X shang" in the second (the first case will now literally translate to "I throw-give you a ball" which is why we have the animacy constraint, while the second literally translates to "I throw the ball toward-cup-near" which is why we have an inanimacy constraint). 

Currently, there was a small bug in the language generator causing it not to generate "gei" in several places where it should have and fixing this in conjunction with the `AFAFAF` implementation allows us to learn "X ba Y reng gei Z" structure since our current throw to template generator has a constraint on the goal that it must be animate. However, I expect that at some stage we will want to learn both throwing to animate and inanimate goals together, in which case the learner could struggle to differentiate between these cases. When exposed to both of these together, this could pose a case of https://github.com/isi-vista/adam/issues/750.

**Comment by LichMaster98** [comment]
@paynesa Can you generate a test case (in a unit test) which shows the new style learner a few instances of  the format "I throw a ball to you" and then the same for "I throw a ball to a box" and then see if the learner can identify both even with the noise? Our current implementation of the verb learner should be ok at this given `animacy` is a marked part of the perception and we don't currently rely on the relation learner to assert the goal location information.

**Comment by paynesa** [comment]
Chinese learns this, but English fails -- see #870
