### ISSUE TITLE
Integrated Learner for Verbs needs to fully respect slot variables

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#867]
After reviewing a complete run of the Integrated Learner with the ObjectRecognizerAsObjectLearner the verb learner produces verb patterns with the name of "slot1_passes_a_watermelon_to_slot2" even though it has a pattern for "slot1_passes_slot2_to_slot3" 

Pattern validity should rule the middle case invalid. Perhaps if we should require a verb template to match the number of matched objects in the scene?

**Comment by gabbard** [comment]
> Perhaps if we should require a verb template to match the number of matched objects in the scene?

This is a little too strong, but could we instead say that the "fixed" portion of a non-object pattern cannot contain tokens aligned to recognized objects?
