### ISSUE TITLE
Integrated Learner for Attributes crashes on trying to process when "a" is detected as an object

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#869]
On the first time we see a color with a complex object (one with sub-objects) it appears our object learner hasn't fully learned to ignore "a" as an object. This causes a problem as both "a" and "house" match to the language of "a white house" as objects. This match becomes valid because "a" replaces a sub-object node inside of the structure for house. (A valid match as this functionality is needed for "hand" in a person). However because we now have two objects, the attribute learner fails because the number of expected matched objects doesn't equal the number of slot fillers in the generated template.

```
Traceback (most recent call last):
  File "/nas/home/jacobl/projects/adam-root/adam/adam/learner/alignments.py", line 230, in to_surface_template
    "We currently only allow for the situation "
RuntimeError: We currently only allow for the situation where every matched object corresponds to a template node.
```

**Comment by gabbard** [comment]
@LichMaster98 : As a temporary measure, I suggest logging a warning here and simply refusing to try to learn from such examples.

**Comment by gabbard** [comment]
@LichMaster98 : Could this be a good task for @paynesa ?

**Comment by LichMaster98** [comment]
@gabbard That sounds like a good idea.

**Comment by LichMaster98** [comment]
Closed by: https://github.com/isi-vista/adam/pull/879
