### ISSUE TITLE
Refine the definition of `SUPPORT` to settle ambiguity between torso and limbs

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#88]
The current definition of the relation support is 

> A relation indicating that one object provides the force to counteract gravity and prevent another object from falling.

However in the case of a limb and torso how does this relationship hold? An example which causes ambiguity is a bird. Wherein when it is perched on a log the legs support the torso which support the head, tail, and wings. By contrast when the bird is flying the wings support the torso which support the head, tail, and legs.

**Comment by rgabbard** [comment]
Removed this relation because Landau and Jackendoff claim it is not required by any English prepositions.
