### ISSUE TITLE
Tall+big and short+small are currently only differentiated with a syntax hint

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#889]
This makes it impossible for our learner to acquire the difference between tall/big and short/small, so the semantics for each look exactly the same.

**Comment by gabbard** [comment]
@paynesa : I think we want to use `tall/short` when the largest/smallest axis of an object is the vertical one and otherwise `big/small`

**Comment by gabbard** [comment]
So we could make that distinction in the semantics
