### ISSUE TITLE
"under" and "over" ground relations 

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#929]
By default in our semantics, both objects are on the ground in an under/over relation, but obviously one cannot be under or over the other if they are on the same horizontal plane.

**Comment by LichMaster98** [comment]
If we add a negated relation to the situations which an object shouldn't be in contact with the ground and check for this relationship when we generated implicit relationships between objects and the ground. While this solution is somewhat of a hack and forces the situation designer to be aware of it, we get detailed control for the designer to specify this condition.

**Comment by mitchmarcus** [comment]
Jacob,

 

What does “shouldn’t” mean here?  Is this in the vision representation?  If so, it’s a pretty big hack if it encodes relevant stuff for just the verb or preposition said.

 

Mitch

**Comment by LichMaster98** [comment]
Hi Mitch! Currently our perception generation tries to implicitly make sure objects are supported by some other object. However in the situation "A box over a table" the perception unit generates the following relations:

over(box, table)
on(box, ground)
on(table, ground)

This perception is a mistake in how we implicitly try to make sure objects are supported by some other object. This initial 'snapshot' is a box that is suspended in the air over the table without being in contact with anything else. If the curriculum designer specifies `not(on(box,ground))` as a situation relation then we could simply use that to filter out a mistake for the implicit perception of all objects being on the ground. If both the table and box are on the ground it's hard to image how the box can also be "over" the table.

**Comment by mitchmarcus** [comment]
Hi Jacob!

 

Thanks!  Yes, this is exactly where this kind of negative is needed, as you say.  It informs the generation of the scene, but nothing else.  And it is exactly necessary.  

 

Mitch
