### ISSUE TITLE
Parallel curriculum generation

### ISSUE THREAD

**Issue by spigo900** [isi-vista/adam#958]
We'd like to be able to run our curriculum generation code on the cluster using Pegasus so that we can save time when running experiments on fixed curricula.

As part of this, we need a way to store our generated curricula, the obvious way being to use Pickle.

One of the difficulties is that pickling the curriculum causes issues with learning. In particular the subset verb learner unit tests run into failures to learn and crashes when they are modified to pickle and unpickle the curricula before using them.

One specific problem with serializing our curricula is that this does not preserve the identity of `eq=False` objects. This is likely one cause of the above errors, because our code makes assumptions like "there is only one GROUND perception." This assumption is violated when we unpickle a perception graph, since the unpickled GROUND perception is distinct from the one we use everywhere else. The object recognizer code [here][object_recognizer_identity_assumption] is one example where this assumption is used and where it would be violated.

[object_recognizer_identity_assumption]: https://github.com/isi-vista/adam/blob/5a3684d33c482b4bad4234b464110c033af05e08/adam/learner/object_recognizer.py#L296

There's another possible problem, namely that if we create our learner in code while unpickling our curriculum, our learner's ontology and our curriculum's ontology will be out of alignment -- they will no longer be equal. However testing suggests that this is not a problem in practice. First, the ontology graph is unaffected. Second, if we pickle and unpickle the learner together with the curricula, it preserves the alignment between their ontologies, but the same problems occur. I saw the same pattern of unit test failures when pickling and unpickling the learner and curricula together.

Overall I suspect the first problem is most likely to be the source of the problems, in particular due to the unit test failures when the learner and the curricula are pickled together, and due to the specific ways the code fails.

The specific failures are:

- `test_drink`
  - Both the English and Chinese tests crash while replacing objects.
  - The crash is due to attempting to get the successors of a node that isn't in the graph.
  - Specifically, the problem seems to be that it tries to get the successors of the `gravitational-up` axis in the graph.
  - It's unclear why this only happens for `drink`.
  - I'll try debugging to see what the problem is in this specific case.
- `test_fall` and `test_throw`
  - Only the English unit tests fail.
  - Both appear to be due to determiner failures.
  - For `test_fall`, it's a determiner failure, likely caused by the first problem above.
  - For `test_throw`, I suspect the problem is the same, because the descriptions include "a ground" rather than "the ground."
    - However, the failure message doesn't include enough words from the expected vs. actual descriptions to be sure.

**Comment by spigo900** [comment]
I've discovered the source of the unit test failure with `test_drink`. It *is* because of the first problem.

It's failing when training on the first example, "Dad drinks juice." Specifically, the problem is that `the ground` doesn't get special-cased, so it gets replaced. It gets replaced before the `juice` does, which means its axes get replaced. This isn't a problem for other tests because most objects have their own axes. However, `juice` (like other substances) uses the world axes, so that means when we look for the axes after replacing the ground, it can't find them and it crashes.

Thus all of the unit test failures I ran into were because of the first problem above. That's good -- it means it's not a deeper failure.

I'm looking into ways to resolve this.

**Comment by spigo900** [comment]
Looking into this, it looks like the best solution is to define a custom pickler/unpickler pair which use `persistent_id()/persistent_load()` to make sure that the shared world items get saved and restored correctly.

Other potential solutions:

1. We could define custom `__getstate__()` and `__setstate__()` methods for our `ObjectPerception` s and  `GeonAx` es that special-case our shared world axes and objects.
    1. This would require disabling `slots` on those classes, which I think would work fine but is worth noting.
        1. That's because `attrs` overrides any custom `__getstate__()` or `__setstate__()` logic you provide if you enable `slots`.
2. We could define pickling methods on the high-level problem objects (`PerceptualRepresentation`, `DevelopmentalPrimitivePerceptionFrame`, and `HighLevelSemanticsSituation`).
    1. I don't know of a good way to make this composable (to where you could easily pickle *a list of tuples* (situation, perception, language) to a single file), so it would make pickling curricula tricky.

**Comment by spigo900** [comment]
Now that pickling is resolved, we want to actually generate the curricula.

It needs to be easy to locate a curriculum. After all, there are a lot of curricula. There may be a lot of experiments. I assume we don't want to have to specify the location of our curriculum file for every experiment. Besides the problem of the initial inconvenience, we might want to change what file we're using. We might want to, for example, change the number of noise objects the experiment uses, which requires using a different curriculum file. Ideally, it should also be easy to switch an experiment between generating the curriculum as it is used and using a pre-generated curriculum, which is easier if the output is structured.

In order to achieve this, we need to organize the curriculum generation output in some way. I propose that we structure the output directory (the _curriculum repository_) like this:

```
{curriculum_name}/
  {language_mode}/
    {num_samples}_samples/
      {num_noise_objects}_noise_objects/
        {some_other_parameter}_name/
          curriculum.pickle
```

The order in which we nest the folders should be deterministic so that it does not depend on how the user ordered the parameters in the parameters file. In order to make sure the repository stays organized correctly there should be functions for reading curricula from and writing curricula to the curriculum repository, defined in (say) `adam.experiment.curriculum_repository`. The functions would take the repository path, the curriculum parameters, and the language mode. The write function would also take the curriculum to write. Both functions would both refer to some constant sequence (an immutable set, say) defining the parameter order.

@denizbeser, do you see any problems with this plan?

I notice one problem myself, thinking about it. How do would our functions notice and raise an error if they are not handling all of the curriculum-related parameters? For example if our parameter-ordering sequence only includes the parameters `num_samples` and `num_noise_objects` but not the pursuit curriculum parameters, then (ideally) it should be able to raise an error when it runs a pursuit curriculum, because there are extra curriculum-related parameters that aren't covered by the ordering sequence. But as written, we can't distinguish between "curriculum parameters that we didn't handle" and "parameters that are totally unrelated to the curriculum" (like `experiment_name`), so we can't actually tell.

Maybe the caller should pass these functions a list of parameters to ignore. This forces them to specify what's *not* related to the curriculum and so we could detect this problem and stop. We wouldn't end up silently overwriting the curriculum.

**Comment by lichtefeld** [comment]
Closing as P1/P2 curriculum generation is not needing for Phase 3 and in general curriculum generation is quick compared to training the learner.
