### ISSUE TITLE
Object matching is very slow for pursuit and integrated learner without object recognizer

### ISSUE THREAD

**Issue by paynesa** [isi-vista/adam#965]
Depending on the object, this can take a long time or recurse infinitely. 

This happens for both the integrated learner without the object recognizer and some parameters of the pursuit curriculum (#962)

This is pending a possible fix from #939 for object matching.

**Comment by lichtefeld** [comment]
P1/2 speed considerations may not map 1:1 to P3 perception graphs. Closing this issue and will reopen with a new one if needed for P3.
